// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/blob.proto

package graphenepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobAlgorithm int32

const (
	BlobAlgorithm_BLOB_ALGORITHM_UNSPECIFIED BlobAlgorithm = 0
	BlobAlgorithm_BLOB_ALGORITHM_SHA256      BlobAlgorithm = 1
)

// Enum value maps for BlobAlgorithm.
var (
	BlobAlgorithm_name = map[int32]string{
		0: "BLOB_ALGORITHM_UNSPECIFIED",
		1: "BLOB_ALGORITHM_SHA256",
	}
	BlobAlgorithm_value = map[string]int32{
		"BLOB_ALGORITHM_UNSPECIFIED": 0,
		"BLOB_ALGORITHM_SHA256":      1,
	}
)

func (x BlobAlgorithm) Enum() *BlobAlgorithm {
	p := new(BlobAlgorithm)
	*p = x
	return p
}

func (x BlobAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlobAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_blob_proto_enumTypes[0].Descriptor()
}

func (BlobAlgorithm) Type() protoreflect.EnumType {
	return &file_v1_blob_proto_enumTypes[0]
}

func (x BlobAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlobAlgorithm.Descriptor instead.
func (BlobAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{0}
}

// BlobRef is where bytes are: an opaque handle the server issued.
type BlobRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{0}
}

func (x *BlobRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// BlobChecksum is what the bytes should hash to.
//
// The algorithm travels with the value because a bare 32 bytes is only
// meaningful to a reader who already agreed which function produced them,
// and "everyone knows it is sha256" is an agreement that lasts until the
// day it does not.
type BlobChecksum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     BlobAlgorithm          `protobuf:"varint,1,opt,name=algorithm,proto3,enum=BlobAlgorithm" json:"algorithm,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobChecksum) Reset() {
	*x = BlobChecksum{}
	mi := &file_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobChecksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobChecksum) ProtoMessage() {}

func (x *BlobChecksum) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobChecksum.ProtoReflect.Descriptor instead.
func (*BlobChecksum) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{1}
}

func (x *BlobChecksum) GetAlgorithm() BlobAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return BlobAlgorithm_BLOB_ALGORITHM_UNSPECIFIED
}

func (x *BlobChecksum) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// BlobInfo is everything known about a blob without reading it.
type BlobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      *BlobChecksum          `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobInfo) Reset() {
	*x = BlobInfo{}
	mi := &file_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobInfo) ProtoMessage() {}

func (x *BlobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobInfo.ProtoReflect.Descriptor instead.
func (*BlobInfo) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{2}
}

func (x *BlobInfo) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *BlobInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobInfo) GetChecksum() *BlobChecksum {
	if x != nil {
		return x.Checksum
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type StatResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Exists bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// Set only when it exists.
	Info          *BlobInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetInfo() *BlobInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*UploadRequest_Open
	//	*UploadRequest_Data
	Frame         isUploadRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRequest) GetFrame() isUploadRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *UploadRequest) GetOpen() *UploadOpen {
	if x != nil {
		if x, ok := x.Frame.(*UploadRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Frame.(*UploadRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadRequest_Frame interface {
	isUploadRequest_Frame()
}

type UploadRequest_Open struct {
	// Exactly one, and first.
	Open *UploadOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type UploadRequest_Data struct {
	// Every frame after it. Order and integrity are the stream's.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadRequest_Open) isUploadRequest_Frame() {}

func (*UploadRequest_Data) isUploadRequest_Frame() {}

// UploadOpen is what the sender knows before sending.
//
// Both fields are optional: a sender that has not read the bytes yet
// cannot know either, and one that has should say, because a declaration
// is what turns a corrupted transfer into a refusal instead of a stored
// blob nobody notices is wrong.
type UploadOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      *BlobChecksum          `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOpen) Reset() {
	*x = UploadOpen{}
	mi := &file_v1_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOpen) ProtoMessage() {}

func (x *UploadOpen) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOpen.ProtoReflect.Descriptor instead.
func (*UploadOpen) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{6}
}

func (x *UploadOpen) GetChecksum() *BlobChecksum {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *UploadOpen) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *BlobInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_v1_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{7}
}

func (x *UploadResponse) GetInfo() *BlobInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Resume a broken transfer: start at this offset.
	Offset        uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_v1_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *DownloadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*DownloadResponse_Info
	//	*DownloadResponse_Data
	Frame         isDownloadResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_v1_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadResponse) GetFrame() isDownloadResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *DownloadResponse) GetInfo() *BlobInfo {
	if x != nil {
		if x, ok := x.Frame.(*DownloadResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Frame.(*DownloadResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDownloadResponse_Frame interface {
	isDownloadResponse_Frame()
}

type DownloadResponse_Info struct {
	// Exactly one, and first.
	Info *BlobInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type DownloadResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DownloadResponse_Info) isDownloadResponse_Frame() {}

func (*DownloadResponse_Data) isDownloadResponse_Frame() {}

type DeleteBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobRequest) Reset() {
	*x = DeleteBlobRequest{}
	mi := &file_v1_blob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobRequest) ProtoMessage() {}

func (x *DeleteBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlobRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBlobRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlobResponse) Reset() {
	*x = DeleteBlobResponse{}
	mi := &file_v1_blob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlobResponse) ProtoMessage() {}

func (x *DeleteBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlobResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlobResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{11}
}

var File_v1_blob_proto protoreflect.FileDescriptor

const file_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\rv1/blob.proto\"\x19\n" +
	"\aBlobRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\fBlobChecksum\x12,\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x0e.BlobAlgorithmR\talgorithm\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"e\n" +
	"\bBlobInfo\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12)\n" +
	"\bchecksum\x18\x03 \x01(\v2\r.BlobChecksumR\bchecksum\")\n" +
	"\vStatRequest\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\"E\n" +
	"\fStatResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1d\n" +
	"\x04info\x18\x02 \x01(\v2\t.BlobInfoR\x04info\"Q\n" +
	"\rUploadRequest\x12!\n" +
	"\x04open\x18\x01 \x01(\v2\v.UploadOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05frame\"K\n" +
	"\n" +
	"UploadOpen\x12)\n" +
	"\bchecksum\x18\x01 \x01(\v2\r.BlobChecksumR\bchecksum\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"/\n" +
	"\x0eUploadResponse\x12\x1d\n" +
	"\x04info\x18\x01 \x01(\v2\t.BlobInfoR\x04info\"E\n" +
	"\x0fDownloadRequest\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"R\n" +
	"\x10DownloadResponse\x12\x1f\n" +
	"\x04info\x18\x01 \x01(\v2\t.BlobInfoH\x00R\x04info\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05frame\"/\n" +
	"\x11DeleteBlobRequest\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\"\x14\n" +
	"\x12DeleteBlobResponse*J\n" +
	"\rBlobAlgorithm\x12\x1e\n" +
	"\x1aBLOB_ALGORITHM_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BLOB_ALGORITHM_SHA256\x10\x012\xc5\x01\n" +
	"\vBlobService\x12#\n" +
	"\x04Stat\x12\f.StatRequest\x1a\r.StatResponse\x12+\n" +
	"\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse(\x01\x121\n" +
	"\bDownload\x12\x10.DownloadRequest\x1a\x11.DownloadResponse0\x01\x121\n" +
	"\x06Delete\x12\x12.DeleteBlobRequest\x1a\x13.DeleteBlobResponseB3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_blob_proto_rawDescOnce sync.Once
	file_v1_blob_proto_rawDescData []byte
)

func file_v1_blob_proto_rawDescGZIP() []byte {
	file_v1_blob_proto_rawDescOnce.Do(func() {
		file_v1_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_blob_proto_rawDesc), len(file_v1_blob_proto_rawDesc)))
	})
	return file_v1_blob_proto_rawDescData
}

var file_v1_blob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_blob_proto_goTypes = []any{
	(BlobAlgorithm)(0),         // 0: BlobAlgorithm
	(*BlobRef)(nil),            // 1: BlobRef
	(*BlobChecksum)(nil),       // 2: BlobChecksum
	(*BlobInfo)(nil),           // 3: BlobInfo
	(*StatRequest)(nil),        // 4: StatRequest
	(*StatResponse)(nil),       // 5: StatResponse
	(*UploadRequest)(nil),      // 6: UploadRequest
	(*UploadOpen)(nil),         // 7: UploadOpen
	(*UploadResponse)(nil),     // 8: UploadResponse
	(*DownloadRequest)(nil),    // 9: DownloadRequest
	(*DownloadResponse)(nil),   // 10: DownloadResponse
	(*DeleteBlobRequest)(nil),  // 11: DeleteBlobRequest
	(*DeleteBlobResponse)(nil), // 12: DeleteBlobResponse
}
var file_v1_blob_proto_depIdxs = []int32{
	0,  // 0: BlobChecksum.algorithm:type_name -> BlobAlgorithm
	1,  // 1: BlobInfo.ref:type_name -> BlobRef
	2,  // 2: BlobInfo.checksum:type_name -> BlobChecksum
	1,  // 3: StatRequest.ref:type_name -> BlobRef
	3,  // 4: StatResponse.info:type_name -> BlobInfo
	7,  // 5: UploadRequest.open:type_name -> UploadOpen
	2,  // 6: UploadOpen.checksum:type_name -> BlobChecksum
	3,  // 7: UploadResponse.info:type_name -> BlobInfo
	1,  // 8: DownloadRequest.ref:type_name -> BlobRef
	3,  // 9: DownloadResponse.info:type_name -> BlobInfo
	1,  // 10: DeleteBlobRequest.ref:type_name -> BlobRef
	4,  // 11: BlobService.Stat:input_type -> StatRequest
	6,  // 12: BlobService.Upload:input_type -> UploadRequest
	9,  // 13: BlobService.Download:input_type -> DownloadRequest
	11, // 14: BlobService.Delete:input_type -> DeleteBlobRequest
	5,  // 15: BlobService.Stat:output_type -> StatResponse
	8,  // 16: BlobService.Upload:output_type -> UploadResponse
	10, // 17: BlobService.Download:output_type -> DownloadResponse
	12, // 18: BlobService.Delete:output_type -> DeleteBlobResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_blob_proto_init() }
func file_v1_blob_proto_init() {
	if File_v1_blob_proto != nil {
		return
	}
	file_v1_blob_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadRequest_Open)(nil),
		(*UploadRequest_Data)(nil),
	}
	file_v1_blob_proto_msgTypes[9].OneofWrappers = []any{
		(*DownloadResponse_Info)(nil),
		(*DownloadResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_blob_proto_rawDesc), len(file_v1_blob_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_blob_proto_goTypes,
		DependencyIndexes: file_v1_blob_proto_depIdxs,
		EnumInfos:         file_v1_blob_proto_enumTypes,
		MessageInfos:      file_v1_blob_proto_msgTypes,
	}.Build()
	File_v1_blob_proto = out.File
	file_v1_blob_proto_goTypes = nil
	file_v1_blob_proto_depIdxs = nil
}
