// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/blob.proto

package graphenepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DigestAlgo int32

const (
	DigestAlgo_DIGEST_ALGO_UNSPECIFIED DigestAlgo = 0
	DigestAlgo_DIGEST_ALGO_SHA256      DigestAlgo = 1
)

// Enum value maps for DigestAlgo.
var (
	DigestAlgo_name = map[int32]string{
		0: "DIGEST_ALGO_UNSPECIFIED",
		1: "DIGEST_ALGO_SHA256",
	}
	DigestAlgo_value = map[string]int32{
		"DIGEST_ALGO_UNSPECIFIED": 0,
		"DIGEST_ALGO_SHA256":      1,
	}
)

func (x DigestAlgo) Enum() *DigestAlgo {
	p := new(DigestAlgo)
	*p = x
	return p
}

func (x DigestAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigestAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_blob_proto_enumTypes[0].Descriptor()
}

func (DigestAlgo) Type() protoreflect.EnumType {
	return &file_v1_blob_proto_enumTypes[0]
}

func (x DigestAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigestAlgo.Descriptor instead.
func (DigestAlgo) EnumDescriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{0}
}

// Digest — an integrity checksum over content. Never an address and never
// a user-facing concept: transfer verification, internal dedup, stable
// cache keys (R19).
type Digest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Algo  DigestAlgo             `protobuf:"varint,1,opt,name=algo,proto3,enum=DigestAlgo" json:"algo,omitempty"`
	// Raw hash bytes (32 bytes for sha256), NOT a hex string.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_v1_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{0}
}

func (x *Digest) GetAlgo() DigestAlgo {
	if x != nil {
		return x.Algo
	}
	return DigestAlgo_DIGEST_ALGO_UNSPECIFIED
}

func (x *Digest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type BlobRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque server-issued handle.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_v1_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{1}
}

func (x *BlobRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlobInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Size  uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Integrity checksum computed by the server. Not an address.
	Checksum      *Digest `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobInfo) Reset() {
	*x = BlobInfo{}
	mi := &file_v1_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobInfo) ProtoMessage() {}

func (x *BlobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobInfo.ProtoReflect.Descriptor instead.
func (*BlobInfo) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{2}
}

func (x *BlobInfo) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *BlobInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlobInfo) GetChecksum() *Digest {
	if x != nil {
		return x.Checksum
	}
	return nil
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*UploadRequest_Open
	//	*UploadRequest_Data
	Msg           isUploadRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_v1_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{3}
}

func (x *UploadRequest) GetMsg() isUploadRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *UploadRequest) GetOpen() *UploadOpen {
	if x != nil {
		if x, ok := x.Msg.(*UploadRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*UploadRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadRequest_Msg interface {
	isUploadRequest_Msg()
}

type UploadRequest_Open struct {
	// Exactly one, first frame.
	Open *UploadOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type UploadRequest_Data struct {
	// All subsequent frames. Ordering and integrity are the stream's
	// job. Recommended frame size 256KiB–1MiB (the transport caps
	// message size).
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadRequest_Open) isUploadRequest_Msg() {}

func (*UploadRequest_Data) isUploadRequest_Msg() {}

type UploadOpen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional declaration: when the sender knows checksum/size upfront
	// the server verifies computed-vs-declared (mismatch = DATA_LOSS, blob
	// not stored). Unknown — leave zero: the server computes them.
	ExpectedChecksum *Digest `protobuf:"bytes,1,opt,name=expected_checksum,json=expectedChecksum,proto3" json:"expected_checksum,omitempty"`
	ExpectedSize     uint64  `protobuf:"varint,2,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadOpen) Reset() {
	*x = UploadOpen{}
	mi := &file_v1_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOpen) ProtoMessage() {}

func (x *UploadOpen) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOpen.ProtoReflect.Descriptor instead.
func (*UploadOpen) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{4}
}

func (x *UploadOpen) GetExpectedChecksum() *Digest {
	if x != nil {
		return x.ExpectedChecksum
	}
	return nil
}

func (x *UploadOpen) GetExpectedSize() uint64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *BlobInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_v1_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{5}
}

func (x *UploadResponse) GetInfo() *BlobInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Resume after a broken stream: send bytes starting at offset.
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Frame size hint; the server may lower it. 0 = server's choice.
	ChunkSize     uint32 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_v1_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *DownloadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadRequest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*DownloadResponse_Info
	//	*DownloadResponse_Data
	Msg           isDownloadResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_v1_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadResponse) GetMsg() isDownloadResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DownloadResponse) GetInfo() *BlobInfo {
	if x != nil {
		if x, ok := x.Msg.(*DownloadResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*DownloadResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDownloadResponse_Msg interface {
	isDownloadResponse_Msg()
}

type DownloadResponse_Info struct {
	// Exactly one, first frame (full size — progress/preallocation).
	Info *BlobInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type DownloadResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DownloadResponse_Info) isDownloadResponse_Msg() {}

func (*DownloadResponse_Data) isDownloadResponse_Msg() {}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *BlobRef               `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_v1_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{8}
}

func (x *StatRequest) GetRef() *BlobRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type StatResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Exists bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// Set only when exists.
	Info          *BlobInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_v1_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_proto_rawDescGZIP(), []int{9}
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetInfo() *BlobInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_v1_blob_proto protoreflect.FileDescriptor

const file_v1_blob_proto_rawDesc = "" +
	"\n" +
	"\rv1/blob.proto\"?\n" +
	"\x06Digest\x12\x1f\n" +
	"\x04algo\x18\x01 \x01(\x0e2\v.DigestAlgoR\x04algo\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x19\n" +
	"\aBlobRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\bBlobInfo\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12#\n" +
	"\bchecksum\x18\x03 \x01(\v2\a.DigestR\bchecksum\"O\n" +
	"\rUploadRequest\x12!\n" +
	"\x04open\x18\x01 \x01(\v2\v.UploadOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"g\n" +
	"\n" +
	"UploadOpen\x124\n" +
	"\x11expected_checksum\x18\x01 \x01(\v2\a.DigestR\x10expectedChecksum\x12#\n" +
	"\rexpected_size\x18\x02 \x01(\x04R\fexpectedSize\"/\n" +
	"\x0eUploadResponse\x12\x1d\n" +
	"\x04info\x18\x01 \x01(\v2\t.BlobInfoR\x04info\"d\n" +
	"\x0fDownloadRequest\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\rR\tchunkSize\"P\n" +
	"\x10DownloadResponse\x12\x1f\n" +
	"\x04info\x18\x01 \x01(\v2\t.BlobInfoH\x00R\x04info\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\")\n" +
	"\vStatRequest\x12\x1a\n" +
	"\x03ref\x18\x01 \x01(\v2\b.BlobRefR\x03ref\"E\n" +
	"\fStatResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1d\n" +
	"\x04info\x18\x02 \x01(\v2\t.BlobInfoR\x04info*A\n" +
	"\n" +
	"DigestAlgo\x12\x1b\n" +
	"\x17DIGEST_ALGO_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DIGEST_ALGO_SHA256\x10\x012\x92\x01\n" +
	"\vBlobService\x12#\n" +
	"\x04Stat\x12\f.StatRequest\x1a\r.StatResponse\x12+\n" +
	"\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse(\x01\x121\n" +
	"\bDownload\x12\x10.DownloadRequest\x1a\x11.DownloadResponse0\x01B3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_blob_proto_rawDescOnce sync.Once
	file_v1_blob_proto_rawDescData []byte
)

func file_v1_blob_proto_rawDescGZIP() []byte {
	file_v1_blob_proto_rawDescOnce.Do(func() {
		file_v1_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_blob_proto_rawDesc), len(file_v1_blob_proto_rawDesc)))
	})
	return file_v1_blob_proto_rawDescData
}

var file_v1_blob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_blob_proto_goTypes = []any{
	(DigestAlgo)(0),          // 0: DigestAlgo
	(*Digest)(nil),           // 1: Digest
	(*BlobRef)(nil),          // 2: BlobRef
	(*BlobInfo)(nil),         // 3: BlobInfo
	(*UploadRequest)(nil),    // 4: UploadRequest
	(*UploadOpen)(nil),       // 5: UploadOpen
	(*UploadResponse)(nil),   // 6: UploadResponse
	(*DownloadRequest)(nil),  // 7: DownloadRequest
	(*DownloadResponse)(nil), // 8: DownloadResponse
	(*StatRequest)(nil),      // 9: StatRequest
	(*StatResponse)(nil),     // 10: StatResponse
}
var file_v1_blob_proto_depIdxs = []int32{
	0,  // 0: Digest.algo:type_name -> DigestAlgo
	2,  // 1: BlobInfo.ref:type_name -> BlobRef
	1,  // 2: BlobInfo.checksum:type_name -> Digest
	5,  // 3: UploadRequest.open:type_name -> UploadOpen
	1,  // 4: UploadOpen.expected_checksum:type_name -> Digest
	3,  // 5: UploadResponse.info:type_name -> BlobInfo
	2,  // 6: DownloadRequest.ref:type_name -> BlobRef
	3,  // 7: DownloadResponse.info:type_name -> BlobInfo
	2,  // 8: StatRequest.ref:type_name -> BlobRef
	3,  // 9: StatResponse.info:type_name -> BlobInfo
	9,  // 10: BlobService.Stat:input_type -> StatRequest
	4,  // 11: BlobService.Upload:input_type -> UploadRequest
	7,  // 12: BlobService.Download:input_type -> DownloadRequest
	10, // 13: BlobService.Stat:output_type -> StatResponse
	6,  // 14: BlobService.Upload:output_type -> UploadResponse
	8,  // 15: BlobService.Download:output_type -> DownloadResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_v1_blob_proto_init() }
func file_v1_blob_proto_init() {
	if File_v1_blob_proto != nil {
		return
	}
	file_v1_blob_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadRequest_Open)(nil),
		(*UploadRequest_Data)(nil),
	}
	file_v1_blob_proto_msgTypes[7].OneofWrappers = []any{
		(*DownloadResponse_Info)(nil),
		(*DownloadResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_blob_proto_rawDesc), len(file_v1_blob_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_blob_proto_goTypes,
		DependencyIndexes: file_v1_blob_proto_depIdxs,
		EnumInfos:         file_v1_blob_proto_enumTypes,
		MessageInfos:      file_v1_blob_proto_msgTypes,
	}.Build()
	File_v1_blob_proto = out.File
	file_v1_blob_proto_goTypes = nil
	file_v1_blob_proto_depIdxs = nil
}
