// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/definition.proto

package graphenepbv1

import (
	schemapb "github.com/gopherex/schemapb/go/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Strength is the lifetime rule a reference carries.
//
// A reference is one relationship — "A points at B" — and the only thing
// that varies is what the pointer means for their lifetimes. Making that
// a parameter rather than a second mechanism is why there is no separate
// owner field on a resource: an owning reference is declared here, like
// any other, on a field of the spec.
//
// The pointer and the rule run in OPPOSITE directions, which is the part
// worth reading twice. A strong reference points at something that must
// outlive it; an owning reference points at something that will take it
// down with it.
type Strength int32

const (
	// STRENGTH_UNSPECIFIED — a reference that did not say. Refused: every
	// other value here is a different answer to "what happens on delete",
	// and there is no safe guess among them.
	Strength_STRENGTH_UNSPECIFIED Strength = 0
	// STRENGTH_STRONG — the target cannot be deleted while this points at
	// it. What referential integrity means, and what install order is
	// derived from.
	Strength_STRENGTH_STRONG Strength = 1
	// STRENGTH_OWNER — the target owns this one: deleting it deletes this
	// too, children before parents. Immutable after creation, because
	// re-pointing it would quietly change who dies with whom.
	Strength_STRENGTH_OWNER Strength = 2
	// STRENGTH_WEAK — a mention and nothing more. The target may be deleted
	// freely and this is left pointing at nothing, which is the whole
	// meaning of weak: it is not checked on write either.
	Strength_STRENGTH_WEAK Strength = 3
)

// Enum value maps for Strength.
var (
	Strength_name = map[int32]string{
		0: "STRENGTH_UNSPECIFIED",
		1: "STRENGTH_STRONG",
		2: "STRENGTH_OWNER",
		3: "STRENGTH_WEAK",
	}
	Strength_value = map[string]int32{
		"STRENGTH_UNSPECIFIED": 0,
		"STRENGTH_STRONG":      1,
		"STRENGTH_OWNER":       2,
		"STRENGTH_WEAK":        3,
	}
)

func (x Strength) Enum() *Strength {
	p := new(Strength)
	*p = x
	return p
}

func (x Strength) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Strength) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_definition_proto_enumTypes[0].Descriptor()
}

func (Strength) Type() protoreflect.EnumType {
	return &file_v1_definition_proto_enumTypes[0]
}

func (x Strength) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Strength.Descriptor instead.
func (Strength) EnumDescriptor() ([]byte, []int) {
	return file_v1_definition_proto_rawDescGZIP(), []int{0}
}

// Definition is the shape of one kind, as stored: its name, the shape of
// its instances' paths, the schemas of their two halves, and the
// references they carry.
//
// The version is HERE and not in the domain type. A definition is a
// shape; which version the store called that shape is the store's
// business, and this message is the store's business. The old code kept
// it inside the definition and then had to zero it out before comparing
// two of them, which was the type saying it did not belong.
type Definition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is what this defines.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Version numbers this shape, monotonically per kind: 1, 2, 3.
	//
	// It is NOT a store revision. A revision moves on every write to
	// anything; a version moves when the shape of one kind changes, and an
	// instance pins the version it was validated against. Confusing them
	// would pin a resource to a moment in time instead of to a schema.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Shape names each position of an instance's path, in order:
	// ["kernel", "name"]. It is what an instance's path is filled from, and
	// what makes a path of the right length under the wrong kind a
	// different path rather than the same one.
	Shape []string `protobuf:"bytes,3,rep,name=shape,proto3" json:"shape,omitempty"`
	// SpecSchema validates what an author asks for.
	SpecSchema *schemapb.Schema `protobuf:"bytes,4,opt,name=spec_schema,json=specSchema,proto3" json:"spec_schema,omitempty"`
	// StatusSchema validates what a controller reports.
	//
	// Every kind has one. A kind whose status is empty says so with a
	// schema that admits no fields, which is a thing to declare and not a
	// thing to leave out: "no status" and "status nobody described" would
	// otherwise be the same value.
	StatusSchema *schemapb.Schema `protobuf:"bytes,5,opt,name=status_schema,json=statusSchema,proto3" json:"status_schema,omitempty"`
	// Refs are the references instances of this kind carry.
	Refs          []*Ref `protobuf:"bytes,6,rep,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_v1_definition_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_definition_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_v1_definition_proto_rawDescGZIP(), []int{0}
}

func (x *Definition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Definition) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Definition) GetShape() []string {
	if x != nil {
		return x.Shape
	}
	return nil
}

func (x *Definition) GetSpecSchema() *schemapb.Schema {
	if x != nil {
		return x.SpecSchema
	}
	return nil
}

func (x *Definition) GetStatusSchema() *schemapb.Schema {
	if x != nil {
		return x.StatusSchema
	}
	return nil
}

func (x *Definition) GetRefs() []*Ref {
	if x != nil {
		return x.Refs
	}
	return nil
}

// Ref declares that one field of a kind points at another kind.
//
// Declared by the definition and not discovered in a value, which is what
// makes referential integrity, install order and garbage collection
// possible before anything has been written.
type Ref struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field is the path to the field that holds the reference, in order:
	// ["spec", "bundle"]. It names fields only — a reference lives at a
	// field, not inside a list element.
	Field []string `protobuf:"bytes,1,rep,name=field,proto3" json:"field,omitempty"`
	// Kind is what the value found there names.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Strength is what happens to the two of them when the target is
	// deleted. There is no default worth having, so a reference that does
	// not say is refused rather than guessed at.
	Strength      Strength `protobuf:"varint,3,opt,name=strength,proto3,enum=Strength" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_v1_definition_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_v1_definition_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_v1_definition_proto_rawDescGZIP(), []int{1}
}

func (x *Ref) GetField() []string {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Ref) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Ref) GetStrength() Strength {
	if x != nil {
		return x.Strength
	}
	return Strength_STRENGTH_UNSPECIFIED
}

var File_v1_definition_proto protoreflect.FileDescriptor

const file_v1_definition_proto_rawDesc = "" +
	"\n" +
	"\x13v1/definition.proto\x1a\x15schemapb/schema.proto\"\xe1\x01\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x14\n" +
	"\x05shape\x18\x03 \x03(\tR\x05shape\x121\n" +
	"\vspec_schema\x18\x04 \x01(\v2\x10.schemapb.SchemaR\n" +
	"specSchema\x125\n" +
	"\rstatus_schema\x18\x05 \x01(\v2\x10.schemapb.SchemaR\fstatusSchema\x12\x18\n" +
	"\x04refs\x18\x06 \x03(\v2\x04.RefR\x04refsJ\x04\b\a\x10\bR\x05blobs\"V\n" +
	"\x03Ref\x12\x14\n" +
	"\x05field\x18\x01 \x03(\tR\x05field\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12%\n" +
	"\bstrength\x18\x03 \x01(\x0e2\t.StrengthR\bstrength*`\n" +
	"\bStrength\x12\x18\n" +
	"\x14STRENGTH_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTRENGTH_STRONG\x10\x01\x12\x12\n" +
	"\x0eSTRENGTH_OWNER\x10\x02\x12\x11\n" +
	"\rSTRENGTH_WEAK\x10\x03B3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_definition_proto_rawDescOnce sync.Once
	file_v1_definition_proto_rawDescData []byte
)

func file_v1_definition_proto_rawDescGZIP() []byte {
	file_v1_definition_proto_rawDescOnce.Do(func() {
		file_v1_definition_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_definition_proto_rawDesc), len(file_v1_definition_proto_rawDesc)))
	})
	return file_v1_definition_proto_rawDescData
}

var file_v1_definition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_definition_proto_goTypes = []any{
	(Strength)(0),           // 0: Strength
	(*Definition)(nil),      // 1: Definition
	(*Ref)(nil),             // 2: Ref
	(*schemapb.Schema)(nil), // 3: schemapb.Schema
}
var file_v1_definition_proto_depIdxs = []int32{
	3, // 0: Definition.spec_schema:type_name -> schemapb.Schema
	3, // 1: Definition.status_schema:type_name -> schemapb.Schema
	2, // 2: Definition.refs:type_name -> Ref
	0, // 3: Ref.strength:type_name -> Strength
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_definition_proto_init() }
func file_v1_definition_proto_init() {
	if File_v1_definition_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_definition_proto_rawDesc), len(file_v1_definition_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_definition_proto_goTypes,
		DependencyIndexes: file_v1_definition_proto_depIdxs,
		EnumInfos:         file_v1_definition_proto_enumTypes,
		MessageInfos:      file_v1_definition_proto_msgTypes,
	}.Build()
	File_v1_definition_proto = out.File
	file_v1_definition_proto_goTypes = nil
	file_v1_definition_proto_depIdxs = nil
}
