// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/head.proto

package graphenepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Head says which published version of a kind is the current one.
//
// One record per kind name, stored apart from the shapes it points at,
// because the two are addressed differently: a head by the kind, a shape
// by the kind and the version. That split is what makes "the current
// version" a single read of an exact key rather than a search for the
// largest of something — and searching is not cheap, because the byte
// layer walks forward only and a key sorts "v10" before "v2".
//
// It is deliberately not a Resource. A resource carries its values in a
// StructValue, which would put this number behind a type assertion on the
// hottest read there is, and would need a definition of its own compiled
// in with an empty spec schema declared only so that a schema would
// exist. It would also have made a kind addressable through the generic
// resource API while its shapes are not — one concept split across two
// surfaces.
//
// The head is written AFTER the shape it points at, never before. Crash
// in between and there is an orphan version nobody looks at, which is
// harmless; the other order leaves a head pointing at nothing.
type Head struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is which kind this is the head of, in the spelling its author
	// chose. The key folds case; this does not.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Version is the published version that is current. Never zero: a head
	// exists because a shape was published, and pointing at version zero
	// would be pointing at the state before any was.
	Version       uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_v1_head_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_v1_head_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_v1_head_proto_rawDescGZIP(), []int{0}
}

func (x *Head) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Head) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_v1_head_proto protoreflect.FileDescriptor

const file_v1_head_proto_rawDesc = "" +
	"\n" +
	"\rv1/head.proto\"4\n" +
	"\x04Head\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversionB3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_head_proto_rawDescOnce sync.Once
	file_v1_head_proto_rawDescData []byte
)

func file_v1_head_proto_rawDescGZIP() []byte {
	file_v1_head_proto_rawDescOnce.Do(func() {
		file_v1_head_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_head_proto_rawDesc), len(file_v1_head_proto_rawDesc)))
	})
	return file_v1_head_proto_rawDescData
}

var file_v1_head_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_head_proto_goTypes = []any{
	(*Head)(nil), // 0: Head
}
var file_v1_head_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_head_proto_init() }
func file_v1_head_proto_init() {
	if File_v1_head_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_head_proto_rawDesc), len(file_v1_head_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_head_proto_goTypes,
		DependencyIndexes: file_v1_head_proto_depIdxs,
		MessageInfos:      file_v1_head_proto_msgTypes,
	}.Build()
	File_v1_head_proto = out.File
	file_v1_head_proto_goTypes = nil
	file_v1_head_proto_depIdxs = nil
}
