// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/id.proto

package graphenepbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Id names one record: which kind it is, and where under that kind it
// lives.
//
// Both halves are needed and neither is enough. Two kinds may shape their
// paths the same way and both have an "/acme/web", so a path alone is
// ambiguous; a kind alone names a whole family.
type Id struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind is the name of the definition this is an instance of.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Path is the filled shape, carrying the position NAMES beside the
	// values.
	//
	// The names are redundant — the definition has them — and are stored
	// anyway, for two reasons.
	//
	// A record stays readable when its definition does not. Deleted,
	// corrupt, not yet replicated: whatever happened to the definition, the
	// resources under it must still be listable, inspectable and
	// removable. Without the names here, a broken registry makes a whole
	// store unreadable.
	//
	// And a record is decoded with the shape it was WRITTEN under, rather
	// than whatever the current version of the kind says. A resource pins
	// the definition version it was admitted against; the shape belongs to
	// that version. Looking the shape up at read time would decode a v1
	// record with a v3 shape and call it the same record.
	//
	// The cost is two short strings per record, beside a spec.
	Path          []*Segment `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_v1_id_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_v1_id_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_v1_id_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Id) GetPath() []*Segment {
	if x != nil {
		return x.Path
	}
	return nil
}

// Segment is one filled position of a path: what it is called, and what
// is in it.
//
// A pair rather than two parallel lists. Two lists can arrive with
// different lengths from a record somebody wrote by hand, and then there
// is no answer to which of them is right.
type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is what the kind calls this position: "kernel", "tenant".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value is what fills it: "local", "acme".
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_v1_id_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_v1_id_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_v1_id_proto_rawDescGZIP(), []int{1}
}

func (x *Segment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Segment) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_v1_id_proto protoreflect.FileDescriptor

const file_v1_id_proto_rawDesc = "" +
	"\n" +
	"\vv1/id.proto\"6\n" +
	"\x02Id\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\x04path\x18\x02 \x03(\v2\b.SegmentR\x04path\"3\n" +
	"\aSegment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_id_proto_rawDescOnce sync.Once
	file_v1_id_proto_rawDescData []byte
)

func file_v1_id_proto_rawDescGZIP() []byte {
	file_v1_id_proto_rawDescOnce.Do(func() {
		file_v1_id_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_id_proto_rawDesc), len(file_v1_id_proto_rawDesc)))
	})
	return file_v1_id_proto_rawDescData
}

var file_v1_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_id_proto_goTypes = []any{
	(*Id)(nil),      // 0: Id
	(*Segment)(nil), // 1: Segment
}
var file_v1_id_proto_depIdxs = []int32{
	1, // 0: Id.path:type_name -> Segment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_id_proto_init() }
func file_v1_id_proto_init() {
	if File_v1_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_id_proto_rawDesc), len(file_v1_id_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_id_proto_goTypes,
		DependencyIndexes: file_v1_id_proto_depIdxs,
		MessageInfos:      file_v1_id_proto_msgTypes,
	}.Build()
	File_v1_id_proto = out.File
	file_v1_id_proto_goTypes = nil
	file_v1_id_proto_depIdxs = nil
}
