// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/kernel.proto

package graphenepbv1

import (
	schemapb "github.com/gopherex/schemapb/go/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventKind is what happened to a record.
type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_KIND_PUT         EventKind = 1
	// EVENT_KIND_DELETE carries what the record LAST was, because whoever
	// filters a stream has to be able to ask what it was that went away.
	EventKind_EVENT_KIND_DELETE EventKind = 2
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EVENT_KIND_UNSPECIFIED",
		1: "EVENT_KIND_PUT",
		2: "EVENT_KIND_DELETE",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_KIND_PUT":         1,
		"EVENT_KIND_DELETE":      2,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_kernel_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_v1_kernel_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{0}
}

// Record is a resource as the store hands it back: the value, and the two
// revisions the store keeps ABOUT it.
//
// The stamps are beside the value and not inside it. A value that could
// hold a revision could hold a stale one, and the revision here is the
// CAS token that goes back out with the next write of this record.
type Record struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Resource *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Revision is what the record is at now, and what a write of it must
	// expect.
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// CreatedRevision is what it was born at. It survives every update and
	// changes on delete-and-recreate, which is what tells a resource from
	// the different one that later took its path.
	CreatedRevision uint64 `protobuf:"varint,3,opt,name=created_revision,json=createdRevision,proto3" json:"created_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_v1_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Record) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Record) GetCreatedRevision() uint64 {
	if x != nil {
		return x.CreatedRevision
	}
	return 0
}

// Event is one change under a watched id.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=EventKind" json:"kind,omitempty"`
	Record        *Record                `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_v1_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

// KindEvent is one change to what is current for a kind.
type KindEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EventKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=EventKind" json:"kind,omitempty"`
	Definition    *Definition            `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KindEvent) Reset() {
	*x = KindEvent{}
	mi := &file_v1_kernel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KindEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KindEvent) ProtoMessage() {}

func (x *KindEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KindEvent.ProtoReflect.Descriptor instead.
func (*KindEvent) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{2}
}

func (x *KindEvent) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *KindEvent) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_kernel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_kernel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Prefix is an id; one with fewer path values than its shape has
	// positions names the subtree beneath it.
	Prefix        *Id `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_v1_kernel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetPrefix() *Id {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_v1_kernel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type WatchRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prefix *Id                    `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// After is where to resume from: the revision the caller last knows
	// about. Zero means from the beginning of what the store still keeps.
	After         uint64 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_v1_kernel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{7}
}

func (x *WatchRequest) GetPrefix() *Id {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *WatchRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_v1_kernel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{8}
}

func (x *WatchResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type RevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionRequest) Reset() {
	*x = RevisionRequest{}
	mi := &file_v1_kernel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionRequest) ProtoMessage() {}

func (x *RevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionRequest.ProtoReflect.Descriptor instead.
func (*RevisionRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{9}
}

type RevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionResponse) Reset() {
	*x = RevisionResponse{}
	mi := &file_v1_kernel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionResponse) ProtoMessage() {}

func (x *RevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionResponse.ProtoReflect.Descriptor instead.
func (*RevisionResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{10}
}

func (x *RevisionResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type HoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldersRequest) Reset() {
	*x = HoldersRequest{}
	mi := &file_v1_kernel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldersRequest) ProtoMessage() {}

func (x *HoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldersRequest.ProtoReflect.Descriptor instead.
func (*HoldersRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{11}
}

func (x *HoldersRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

// Holder is one resource pointing at another.
type Holder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Strength is what this pointer means for the two lifetimes: whether it
	// refuses the target's deletion, follows it, or neither.
	Strength      Strength `protobuf:"varint,2,opt,name=strength,proto3,enum=Strength" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Holder) Reset() {
	*x = Holder{}
	mi := &file_v1_kernel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Holder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holder) ProtoMessage() {}

func (x *Holder) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holder.ProtoReflect.Descriptor instead.
func (*Holder) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{12}
}

func (x *Holder) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Holder) GetStrength() Strength {
	if x != nil {
		return x.Strength
	}
	return Strength_STRENGTH_UNSPECIFIED
}

type HoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holders       []*Holder              `protobuf:"bytes,1,rep,name=holders,proto3" json:"holders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldersResponse) Reset() {
	*x = HoldersResponse{}
	mi := &file_v1_kernel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldersResponse) ProtoMessage() {}

func (x *HoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldersResponse.ProtoReflect.Descriptor instead.
func (*HoldersResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{13}
}

func (x *HoldersResponse) GetHolders() []*Holder {
	if x != nil {
		return x.Holders
	}
	return nil
}

// The expectation every write carries.
//
// It is the revision the caller READ, and zero means "nothing is there
// yet" — a create. There is no unconditional write: two writers settling
// a race without a lock between them is the whole reason a revision
// exists, and an override would be a way around somebody else's decision.
type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Spec is what the author asks for. Everything else about a resource is
	// somebody else's — the generation, the pinned version, the claims, the
	// status — and none of them are here, which is what makes it impossible
	// to send one rather than merely ignored.
	Spec          *schemapb.StructValue `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Expect        uint64                `protobuf:"varint,3,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_v1_kernel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{14}
}

func (x *PutRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PutRequest) GetSpec() *schemapb.StructValue {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *PutRequest) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        *schemapb.StructValue  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Expect        uint64                 `protobuf:"varint,3,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_v1_kernel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{15}
}

func (x *ReportRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ReportRequest) GetStatus() *schemapb.StructValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ReportRequest) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

// Release takes the same three fields Claim does, in a message of its
// own: they are two calls under two permissions, and sharing a request
// would make them look like one call with a flag.
type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Finalizer     string                 `protobuf:"bytes,2,opt,name=finalizer,proto3" json:"finalizer,omitempty"`
	Expect        uint64                 `protobuf:"varint,3,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_v1_kernel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{16}
}

func (x *ReleaseRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ReleaseRequest) GetFinalizer() string {
	if x != nil {
		return x.Finalizer
	}
	return ""
}

func (x *ReleaseRequest) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

type ClaimRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Finalizer names the claim. Placing one twice, or releasing one that
	// was never placed, changes nothing and is not an error: a controller
	// unwinding and starting again should not have to remember whether it
	// already did.
	Finalizer     string `protobuf:"bytes,2,opt,name=finalizer,proto3" json:"finalizer,omitempty"`
	Expect        uint64 `protobuf:"varint,3,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_v1_kernel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{17}
}

func (x *ClaimRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ClaimRequest) GetFinalizer() string {
	if x != nil {
		return x.Finalizer
	}
	return ""
}

func (x *ClaimRequest) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *Id                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Expect        uint64                 `protobuf:"varint,2,opt,name=expect,proto3" json:"expect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_kernel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRequest) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeleteRequest) GetExpect() uint64 {
	if x != nil {
		return x.Expect
	}
	return 0
}

// Every write answers with where it landed, and each answers in a message
// of its own rather than in one they share.
//
// They are identical today and that is not the point. A field added for
// one of them would appear on all of them, and a caller reading it would
// have no way to know which of the five it was ever set by. One message
// per call is what lets them stop being identical.
//
// A delete has a revision too: removing a record is a write, and
// something watching needs to know when it happened.
type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_v1_kernel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{19}
}

func (x *PutResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_v1_kernel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{20}
}

func (x *ReportResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_v1_kernel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{21}
}

func (x *ClaimResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_v1_kernel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{22}
}

func (x *ReleaseResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_v1_kernel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DefineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Definition carries no version on the way in — which version this
	// becomes is the store's word, and the answer comes back in the reply.
	Definition    *Definition `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefineRequest) Reset() {
	*x = DefineRequest{}
	mi := &file_v1_kernel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefineRequest) ProtoMessage() {}

func (x *DefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefineRequest.ProtoReflect.Descriptor instead.
func (*DefineRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{24}
}

func (x *DefineRequest) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type DefineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Definition is what is current now, version and all. Declaring an
	// unchanged shape answers with the version that was already there.
	Definition    *Definition `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefineResponse) Reset() {
	*x = DefineResponse{}
	mi := &file_v1_kernel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefineResponse) ProtoMessage() {}

func (x *DefineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefineResponse.ProtoReflect.Descriptor instead.
func (*DefineResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{25}
}

func (x *DefineResponse) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type UndefineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndefineRequest) Reset() {
	*x = UndefineRequest{}
	mi := &file_v1_kernel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndefineRequest) ProtoMessage() {}

func (x *UndefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndefineRequest.ProtoReflect.Descriptor instead.
func (*UndefineRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{26}
}

func (x *UndefineRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type UndefineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndefineResponse) Reset() {
	*x = UndefineResponse{}
	mi := &file_v1_kernel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndefineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndefineResponse) ProtoMessage() {}

func (x *UndefineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndefineResponse.ProtoReflect.Descriptor instead.
func (*UndefineResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{27}
}

type GetDefinitionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Version is which shape, zero meaning whichever is current.
	Version       uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionRequest) Reset() {
	*x = GetDefinitionRequest{}
	mi := &file_v1_kernel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionRequest) ProtoMessage() {}

func (x *GetDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{28}
}

func (x *GetDefinitionRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetDefinitionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *Definition            `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionResponse) Reset() {
	*x = GetDefinitionResponse{}
	mi := &file_v1_kernel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionResponse) ProtoMessage() {}

func (x *GetDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionResponse.ProtoReflect.Descriptor instead.
func (*GetDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{29}
}

func (x *GetDefinitionResponse) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type ListKindsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKindsRequest) Reset() {
	*x = ListKindsRequest{}
	mi := &file_v1_kernel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsRequest) ProtoMessage() {}

func (x *ListKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsRequest.ProtoReflect.Descriptor instead.
func (*ListKindsRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{30}
}

type ListKindsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *Definition            `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKindsResponse) Reset() {
	*x = ListKindsResponse{}
	mi := &file_v1_kernel_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKindsResponse) ProtoMessage() {}

func (x *ListKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKindsResponse.ProtoReflect.Descriptor instead.
func (*ListKindsResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{31}
}

func (x *ListKindsResponse) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type WatchKindsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind narrows the watch to one of them; empty follows all.
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	After         uint64 `protobuf:"varint,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchKindsRequest) Reset() {
	*x = WatchKindsRequest{}
	mi := &file_v1_kernel_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchKindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchKindsRequest) ProtoMessage() {}

func (x *WatchKindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchKindsRequest.ProtoReflect.Descriptor instead.
func (*WatchKindsRequest) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{32}
}

func (x *WatchKindsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WatchKindsRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

type WatchKindsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *KindEvent             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchKindsResponse) Reset() {
	*x = WatchKindsResponse{}
	mi := &file_v1_kernel_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchKindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchKindsResponse) ProtoMessage() {}

func (x *WatchKindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_kernel_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchKindsResponse.ProtoReflect.Descriptor instead.
func (*WatchKindsResponse) Descriptor() ([]byte, []int) {
	return file_v1_kernel_proto_rawDescGZIP(), []int{33}
}

func (x *WatchKindsResponse) GetEvent() *KindEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_v1_kernel_proto protoreflect.FileDescriptor

const file_v1_kernel_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/kernel.proto\x1a\x14schemapb/value.proto\x1a\x13v1/definition.proto\x1a\vv1/id.proto\x1a\x11v1/resource.proto\"v\n" +
	"\x06Record\x12%\n" +
	"\bresource\x18\x01 \x01(\v2\t.ResourceR\bresource\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12)\n" +
	"\x10created_revision\x18\x03 \x01(\x04R\x0fcreatedRevision\"H\n" +
	"\x05Event\x12\x1e\n" +
	"\x04kind\x18\x01 \x01(\x0e2\n" +
	".EventKindR\x04kind\x12\x1f\n" +
	"\x06record\x18\x02 \x01(\v2\a.RecordR\x06record\"X\n" +
	"\tKindEvent\x12\x1e\n" +
	"\x04kind\x18\x01 \x01(\x0e2\n" +
	".EventKindR\x04kind\x12+\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\v.DefinitionR\n" +
	"definition\"!\n" +
	"\n" +
	"GetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\".\n" +
	"\vGetResponse\x12\x1f\n" +
	"\x06record\x18\x01 \x01(\v2\a.RecordR\x06record\"*\n" +
	"\vListRequest\x12\x1b\n" +
	"\x06prefix\x18\x01 \x01(\v2\x03.IdR\x06prefix\"/\n" +
	"\fListResponse\x12\x1f\n" +
	"\x06record\x18\x01 \x01(\v2\a.RecordR\x06record\"A\n" +
	"\fWatchRequest\x12\x1b\n" +
	"\x06prefix\x18\x01 \x01(\v2\x03.IdR\x06prefix\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\"-\n" +
	"\rWatchResponse\x12\x1c\n" +
	"\x05event\x18\x01 \x01(\v2\x06.EventR\x05event\"\x11\n" +
	"\x0fRevisionRequest\".\n" +
	"\x10RevisionResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"%\n" +
	"\x0eHoldersRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\"D\n" +
	"\x06Holder\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12%\n" +
	"\bstrength\x18\x02 \x01(\x0e2\t.StrengthR\bstrength\"4\n" +
	"\x0fHoldersResponse\x12!\n" +
	"\aholders\x18\x01 \x03(\v2\a.HolderR\aholders\"d\n" +
	"\n" +
	"PutRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12)\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x04spec\x12\x16\n" +
	"\x06expect\x18\x03 \x01(\x04R\x06expect\"k\n" +
	"\rReportRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x06status\x12\x16\n" +
	"\x06expect\x18\x03 \x01(\x04R\x06expect\"[\n" +
	"\x0eReleaseRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12\x1c\n" +
	"\tfinalizer\x18\x02 \x01(\tR\tfinalizer\x12\x16\n" +
	"\x06expect\x18\x03 \x01(\x04R\x06expect\"Y\n" +
	"\fClaimRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12\x1c\n" +
	"\tfinalizer\x18\x02 \x01(\tR\tfinalizer\x12\x16\n" +
	"\x06expect\x18\x03 \x01(\x04R\x06expect\"<\n" +
	"\rDeleteRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12\x16\n" +
	"\x06expect\x18\x02 \x01(\x04R\x06expect\")\n" +
	"\vPutResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\",\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"+\n" +
	"\rClaimResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"-\n" +
	"\x0fReleaseResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\",\n" +
	"\x0eDeleteResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\"<\n" +
	"\rDefineRequest\x12+\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\v.DefinitionR\n" +
	"definition\"=\n" +
	"\x0eDefineResponse\x12+\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\v.DefinitionR\n" +
	"definition\"%\n" +
	"\x0fUndefineRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\x12\n" +
	"\x10UndefineResponse\"D\n" +
	"\x14GetDefinitionRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"D\n" +
	"\x15GetDefinitionResponse\x12+\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\v.DefinitionR\n" +
	"definition\"\x12\n" +
	"\x10ListKindsRequest\"@\n" +
	"\x11ListKindsResponse\x12+\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\v.DefinitionR\n" +
	"definition\"=\n" +
	"\x11WatchKindsRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05after\x18\x02 \x01(\x04R\x05after\"6\n" +
	"\x12WatchKindsResponse\x12 \n" +
	"\x05event\x18\x01 \x01(\v2\n" +
	".KindEventR\x05event*R\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_KIND_PUT\x10\x01\x12\x15\n" +
	"\x11EVENT_KIND_DELETE\x10\x022\xba\x05\n" +
	"\rKernelService\x12 \n" +
	"\x03Get\x12\v.GetRequest\x1a\f.GetResponse\x12%\n" +
	"\x04List\x12\f.ListRequest\x1a\r.ListResponse0\x01\x12(\n" +
	"\x05Watch\x12\r.WatchRequest\x1a\x0e.WatchResponse0\x01\x12/\n" +
	"\bRevision\x12\x10.RevisionRequest\x1a\x11.RevisionResponse\x12,\n" +
	"\aHolders\x12\x0f.HoldersRequest\x1a\x10.HoldersResponse\x12 \n" +
	"\x03Put\x12\v.PutRequest\x1a\f.PutResponse\x12)\n" +
	"\x06Report\x12\x0e.ReportRequest\x1a\x0f.ReportResponse\x12&\n" +
	"\x05Claim\x12\r.ClaimRequest\x1a\x0e.ClaimResponse\x12,\n" +
	"\aRelease\x12\x0f.ReleaseRequest\x1a\x10.ReleaseResponse\x12)\n" +
	"\x06Delete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\x12)\n" +
	"\x06Define\x12\x0e.DefineRequest\x1a\x0f.DefineResponse\x12/\n" +
	"\bUndefine\x12\x10.UndefineRequest\x1a\x11.UndefineResponse\x12>\n" +
	"\rGetDefinition\x12\x15.GetDefinitionRequest\x1a\x16.GetDefinitionResponse\x124\n" +
	"\tListKinds\x12\x11.ListKindsRequest\x1a\x12.ListKindsResponse0\x01\x127\n" +
	"\n" +
	"WatchKinds\x12\x12.WatchKindsRequest\x1a\x13.WatchKindsResponse0\x01B3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_kernel_proto_rawDescOnce sync.Once
	file_v1_kernel_proto_rawDescData []byte
)

func file_v1_kernel_proto_rawDescGZIP() []byte {
	file_v1_kernel_proto_rawDescOnce.Do(func() {
		file_v1_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_kernel_proto_rawDesc), len(file_v1_kernel_proto_rawDesc)))
	})
	return file_v1_kernel_proto_rawDescData
}

var file_v1_kernel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_v1_kernel_proto_goTypes = []any{
	(EventKind)(0),                // 0: EventKind
	(*Record)(nil),                // 1: Record
	(*Event)(nil),                 // 2: Event
	(*KindEvent)(nil),             // 3: KindEvent
	(*GetRequest)(nil),            // 4: GetRequest
	(*GetResponse)(nil),           // 5: GetResponse
	(*ListRequest)(nil),           // 6: ListRequest
	(*ListResponse)(nil),          // 7: ListResponse
	(*WatchRequest)(nil),          // 8: WatchRequest
	(*WatchResponse)(nil),         // 9: WatchResponse
	(*RevisionRequest)(nil),       // 10: RevisionRequest
	(*RevisionResponse)(nil),      // 11: RevisionResponse
	(*HoldersRequest)(nil),        // 12: HoldersRequest
	(*Holder)(nil),                // 13: Holder
	(*HoldersResponse)(nil),       // 14: HoldersResponse
	(*PutRequest)(nil),            // 15: PutRequest
	(*ReportRequest)(nil),         // 16: ReportRequest
	(*ReleaseRequest)(nil),        // 17: ReleaseRequest
	(*ClaimRequest)(nil),          // 18: ClaimRequest
	(*DeleteRequest)(nil),         // 19: DeleteRequest
	(*PutResponse)(nil),           // 20: PutResponse
	(*ReportResponse)(nil),        // 21: ReportResponse
	(*ClaimResponse)(nil),         // 22: ClaimResponse
	(*ReleaseResponse)(nil),       // 23: ReleaseResponse
	(*DeleteResponse)(nil),        // 24: DeleteResponse
	(*DefineRequest)(nil),         // 25: DefineRequest
	(*DefineResponse)(nil),        // 26: DefineResponse
	(*UndefineRequest)(nil),       // 27: UndefineRequest
	(*UndefineResponse)(nil),      // 28: UndefineResponse
	(*GetDefinitionRequest)(nil),  // 29: GetDefinitionRequest
	(*GetDefinitionResponse)(nil), // 30: GetDefinitionResponse
	(*ListKindsRequest)(nil),      // 31: ListKindsRequest
	(*ListKindsResponse)(nil),     // 32: ListKindsResponse
	(*WatchKindsRequest)(nil),     // 33: WatchKindsRequest
	(*WatchKindsResponse)(nil),    // 34: WatchKindsResponse
	(*Resource)(nil),              // 35: Resource
	(*Definition)(nil),            // 36: Definition
	(*Id)(nil),                    // 37: Id
	(Strength)(0),                 // 38: Strength
	(*schemapb.StructValue)(nil),  // 39: schemapb.StructValue
}
var file_v1_kernel_proto_depIdxs = []int32{
	35, // 0: Record.resource:type_name -> Resource
	0,  // 1: Event.kind:type_name -> EventKind
	1,  // 2: Event.record:type_name -> Record
	0,  // 3: KindEvent.kind:type_name -> EventKind
	36, // 4: KindEvent.definition:type_name -> Definition
	37, // 5: GetRequest.id:type_name -> Id
	1,  // 6: GetResponse.record:type_name -> Record
	37, // 7: ListRequest.prefix:type_name -> Id
	1,  // 8: ListResponse.record:type_name -> Record
	37, // 9: WatchRequest.prefix:type_name -> Id
	2,  // 10: WatchResponse.event:type_name -> Event
	37, // 11: HoldersRequest.id:type_name -> Id
	37, // 12: Holder.id:type_name -> Id
	38, // 13: Holder.strength:type_name -> Strength
	13, // 14: HoldersResponse.holders:type_name -> Holder
	37, // 15: PutRequest.id:type_name -> Id
	39, // 16: PutRequest.spec:type_name -> schemapb.StructValue
	37, // 17: ReportRequest.id:type_name -> Id
	39, // 18: ReportRequest.status:type_name -> schemapb.StructValue
	37, // 19: ReleaseRequest.id:type_name -> Id
	37, // 20: ClaimRequest.id:type_name -> Id
	37, // 21: DeleteRequest.id:type_name -> Id
	36, // 22: DefineRequest.definition:type_name -> Definition
	36, // 23: DefineResponse.definition:type_name -> Definition
	36, // 24: GetDefinitionResponse.definition:type_name -> Definition
	36, // 25: ListKindsResponse.definition:type_name -> Definition
	3,  // 26: WatchKindsResponse.event:type_name -> KindEvent
	4,  // 27: KernelService.Get:input_type -> GetRequest
	6,  // 28: KernelService.List:input_type -> ListRequest
	8,  // 29: KernelService.Watch:input_type -> WatchRequest
	10, // 30: KernelService.Revision:input_type -> RevisionRequest
	12, // 31: KernelService.Holders:input_type -> HoldersRequest
	15, // 32: KernelService.Put:input_type -> PutRequest
	16, // 33: KernelService.Report:input_type -> ReportRequest
	18, // 34: KernelService.Claim:input_type -> ClaimRequest
	17, // 35: KernelService.Release:input_type -> ReleaseRequest
	19, // 36: KernelService.Delete:input_type -> DeleteRequest
	25, // 37: KernelService.Define:input_type -> DefineRequest
	27, // 38: KernelService.Undefine:input_type -> UndefineRequest
	29, // 39: KernelService.GetDefinition:input_type -> GetDefinitionRequest
	31, // 40: KernelService.ListKinds:input_type -> ListKindsRequest
	33, // 41: KernelService.WatchKinds:input_type -> WatchKindsRequest
	5,  // 42: KernelService.Get:output_type -> GetResponse
	7,  // 43: KernelService.List:output_type -> ListResponse
	9,  // 44: KernelService.Watch:output_type -> WatchResponse
	11, // 45: KernelService.Revision:output_type -> RevisionResponse
	14, // 46: KernelService.Holders:output_type -> HoldersResponse
	20, // 47: KernelService.Put:output_type -> PutResponse
	21, // 48: KernelService.Report:output_type -> ReportResponse
	22, // 49: KernelService.Claim:output_type -> ClaimResponse
	23, // 50: KernelService.Release:output_type -> ReleaseResponse
	24, // 51: KernelService.Delete:output_type -> DeleteResponse
	26, // 52: KernelService.Define:output_type -> DefineResponse
	28, // 53: KernelService.Undefine:output_type -> UndefineResponse
	30, // 54: KernelService.GetDefinition:output_type -> GetDefinitionResponse
	32, // 55: KernelService.ListKinds:output_type -> ListKindsResponse
	34, // 56: KernelService.WatchKinds:output_type -> WatchKindsResponse
	42, // [42:57] is the sub-list for method output_type
	27, // [27:42] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_v1_kernel_proto_init() }
func file_v1_kernel_proto_init() {
	if File_v1_kernel_proto != nil {
		return
	}
	file_v1_definition_proto_init()
	file_v1_id_proto_init()
	file_v1_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_kernel_proto_rawDesc), len(file_v1_kernel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_kernel_proto_goTypes,
		DependencyIndexes: file_v1_kernel_proto_depIdxs,
		EnumInfos:         file_v1_kernel_proto_enumTypes,
		MessageInfos:      file_v1_kernel_proto_msgTypes,
	}.Build()
	File_v1_kernel_proto = out.File
	file_v1_kernel_proto_goTypes = nil
	file_v1_kernel_proto_depIdxs = nil
}
