// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/kernel.proto

package graphenepbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelService_Get_FullMethodName           = "/KernelService/Get"
	KernelService_List_FullMethodName          = "/KernelService/List"
	KernelService_Watch_FullMethodName         = "/KernelService/Watch"
	KernelService_Revision_FullMethodName      = "/KernelService/Revision"
	KernelService_Holders_FullMethodName       = "/KernelService/Holders"
	KernelService_Put_FullMethodName           = "/KernelService/Put"
	KernelService_Report_FullMethodName        = "/KernelService/Report"
	KernelService_Claim_FullMethodName         = "/KernelService/Claim"
	KernelService_Release_FullMethodName       = "/KernelService/Release"
	KernelService_Delete_FullMethodName        = "/KernelService/Delete"
	KernelService_Define_FullMethodName        = "/KernelService/Define"
	KernelService_Undefine_FullMethodName      = "/KernelService/Undefine"
	KernelService_GetDefinition_FullMethodName = "/KernelService/GetDefinition"
	KernelService_ListKinds_FullMethodName     = "/KernelService/ListKinds"
	KernelService_WatchKinds_FullMethodName    = "/KernelService/WatchKinds"
)

// KernelServiceClient is the client API for KernelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The kernel, on a wire.
//
// Every method below is a method the kernel already has, and it is here
// because the kernel has it — not because a client wanted it. That is the
// whole rule this file was written under: a CLI, an agent and a
// controller are all clients, and an API shaped by whichever of them was
// written first is an API that has to be reshaped for the second.
//
// So the check runs the other way. If a client cannot be built on this,
// either it is asking for something the model does not have — and the
// client is what changes — or the model is missing something, and that is
// a decision to take deliberately and somewhere else.
//
// The verbs are also the permissions. Get, List, Watch, Put, Report,
// Claim, Release, Delete, Define and Undefine are each a method, each an
// RPC, and each a grant, one for one. A refusal therefore names the same
// word the call did, which the alternative — a friendlier verb on the
// outside — cannot do.
type KernelServiceClient interface {
	// Get reads one resource, with the revision it is at.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// List walks everything under an id, in key order.
	//
	// An id with fewer path values than its shape has positions is a
	// subtree, which is what makes this the same call as reading one thing.
	// Streamed rather than paged: the kernel walks an iterator and a stream
	// is that with the network in it, while a page needs a cursor nothing
	// underneath has.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListResponse], error)
	// Watch follows changes under an id.
	//
	// It delivers NO snapshot, and a caller that wants one takes it in
	// three calls: Revision first, List second, Watch third. A write
	// between the first two is then seen twice rather than not at all, and
	// a reconciling consumer is built to be told twice. A watch that opened
	// with a snapshot would have to deliver it as events, whose revisions
	// are each key's last write and therefore not in order — so resuming
	// from one would silently lose whatever sorted after it.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
	// Revision is the store-wide revision as of now: the cursor to take
	// before a snapshot.
	Revision(ctx context.Context, in *RevisionRequest, opts ...grpc.CallOption) (*RevisionResponse, error)
	// Holders is what points at a resource, and what those pointers mean
	// for its lifetime.
	//
	// The model's question rather than any client's: a reference carries a
	// strength, and a strength is a statement about two lifetimes. It is
	// also the answer to the one a refused delete raises.
	Holders(ctx context.Context, in *HoldersRequest, opts ...grpc.CallOption) (*HoldersResponse, error)
	// Put writes what an author asked for: the spec, and nothing else.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	// Report records what a controller found. Separate from Put because it
	// is a different party writing a different half, and because it must
	// not move the generation — a status write that counted as intent would
	// wake the controller that wrote it, forever.
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	// Claim places a claim on a resource's deletion, and Release lets go of
	// one. Separate for the same reason Report is: whoever will do the
	// cleaning is rarely whoever wrote the spec, and the permission to hold
	// a resource open should not carry the permission to rewrite it.
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// Delete asks a resource to go away. Whether it goes at once or waits
	// is the resource's answer and not the caller's: with claims on it the
	// record stays, marked, until they are released.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Define publishes a shape for a kind and makes it current. It is
	// idempotent against the shape: declaring the same definition twice
	// leaves one version.
	Define(ctx context.Context, in *DefineRequest, opts ...grpc.CallOption) (*DefineResponse, error)
	// Undefine removes a kind and every version of it, and refuses while
	// any instance is left.
	Undefine(ctx context.Context, in *UndefineRequest, opts ...grpc.CallOption) (*UndefineResponse, error)
	// GetDefinition is a kind's current shape — one read of an exact key,
	// which is what the head record exists to make possible. With a version
	// it is the shape as it was, which is what a resource pins and what
	// anything reading an older instance has to validate against.
	GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*GetDefinitionResponse, error)
	// ListKinds walks every kind that has been defined.
	ListKinds(ctx context.Context, in *ListKindsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListKindsResponse], error)
	// WatchKinds follows what is current. With a kind named, one of them;
	// without, all. A change to a head IS a change to the current
	// definition, so publishing a version that does not become current
	// says nothing here — which is right, because nothing about the kind
	// changed.
	WatchKinds(ctx context.Context, in *WatchKindsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchKindsResponse], error)
}

type kernelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelServiceClient(cc grpc.ClientConnInterface) KernelServiceClient {
	return &kernelServiceClient{cc}
}

func (c *kernelServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, KernelService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelService_ServiceDesc.Streams[0], KernelService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListRequest, ListResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_ListClient = grpc.ServerStreamingClient[ListResponse]

func (c *kernelServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelService_ServiceDesc.Streams[1], KernelService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_WatchClient = grpc.ServerStreamingClient[WatchResponse]

func (c *kernelServiceClient) Revision(ctx context.Context, in *RevisionRequest, opts ...grpc.CallOption) (*RevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevisionResponse)
	err := c.cc.Invoke(ctx, KernelService_Revision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Holders(ctx context.Context, in *HoldersRequest, opts ...grpc.CallOption) (*HoldersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoldersResponse)
	err := c.cc.Invoke(ctx, KernelService_Holders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, KernelService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, KernelService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, KernelService_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, KernelService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, KernelService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Define(ctx context.Context, in *DefineRequest, opts ...grpc.CallOption) (*DefineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefineResponse)
	err := c.cc.Invoke(ctx, KernelService_Define_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) Undefine(ctx context.Context, in *UndefineRequest, opts ...grpc.CallOption) (*UndefineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndefineResponse)
	err := c.cc.Invoke(ctx, KernelService_Undefine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) GetDefinition(ctx context.Context, in *GetDefinitionRequest, opts ...grpc.CallOption) (*GetDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDefinitionResponse)
	err := c.cc.Invoke(ctx, KernelService_GetDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ListKinds(ctx context.Context, in *ListKindsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListKindsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelService_ServiceDesc.Streams[2], KernelService_ListKinds_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListKindsRequest, ListKindsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_ListKindsClient = grpc.ServerStreamingClient[ListKindsResponse]

func (c *kernelServiceClient) WatchKinds(ctx context.Context, in *WatchKindsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchKindsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelService_ServiceDesc.Streams[3], KernelService_WatchKinds_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchKindsRequest, WatchKindsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_WatchKindsClient = grpc.ServerStreamingClient[WatchKindsResponse]

// KernelServiceServer is the server API for KernelService service.
// All implementations must embed UnimplementedKernelServiceServer
// for forward compatibility.
//
// The kernel, on a wire.
//
// Every method below is a method the kernel already has, and it is here
// because the kernel has it — not because a client wanted it. That is the
// whole rule this file was written under: a CLI, an agent and a
// controller are all clients, and an API shaped by whichever of them was
// written first is an API that has to be reshaped for the second.
//
// So the check runs the other way. If a client cannot be built on this,
// either it is asking for something the model does not have — and the
// client is what changes — or the model is missing something, and that is
// a decision to take deliberately and somewhere else.
//
// The verbs are also the permissions. Get, List, Watch, Put, Report,
// Claim, Release, Delete, Define and Undefine are each a method, each an
// RPC, and each a grant, one for one. A refusal therefore names the same
// word the call did, which the alternative — a friendlier verb on the
// outside — cannot do.
type KernelServiceServer interface {
	// Get reads one resource, with the revision it is at.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// List walks everything under an id, in key order.
	//
	// An id with fewer path values than its shape has positions is a
	// subtree, which is what makes this the same call as reading one thing.
	// Streamed rather than paged: the kernel walks an iterator and a stream
	// is that with the network in it, while a page needs a cursor nothing
	// underneath has.
	List(*ListRequest, grpc.ServerStreamingServer[ListResponse]) error
	// Watch follows changes under an id.
	//
	// It delivers NO snapshot, and a caller that wants one takes it in
	// three calls: Revision first, List second, Watch third. A write
	// between the first two is then seen twice rather than not at all, and
	// a reconciling consumer is built to be told twice. A watch that opened
	// with a snapshot would have to deliver it as events, whose revisions
	// are each key's last write and therefore not in order — so resuming
	// from one would silently lose whatever sorted after it.
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	// Revision is the store-wide revision as of now: the cursor to take
	// before a snapshot.
	Revision(context.Context, *RevisionRequest) (*RevisionResponse, error)
	// Holders is what points at a resource, and what those pointers mean
	// for its lifetime.
	//
	// The model's question rather than any client's: a reference carries a
	// strength, and a strength is a statement about two lifetimes. It is
	// also the answer to the one a refused delete raises.
	Holders(context.Context, *HoldersRequest) (*HoldersResponse, error)
	// Put writes what an author asked for: the spec, and nothing else.
	Put(context.Context, *PutRequest) (*PutResponse, error)
	// Report records what a controller found. Separate from Put because it
	// is a different party writing a different half, and because it must
	// not move the generation — a status write that counted as intent would
	// wake the controller that wrote it, forever.
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	// Claim places a claim on a resource's deletion, and Release lets go of
	// one. Separate for the same reason Report is: whoever will do the
	// cleaning is rarely whoever wrote the spec, and the permission to hold
	// a resource open should not carry the permission to rewrite it.
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// Delete asks a resource to go away. Whether it goes at once or waits
	// is the resource's answer and not the caller's: with claims on it the
	// record stays, marked, until they are released.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Define publishes a shape for a kind and makes it current. It is
	// idempotent against the shape: declaring the same definition twice
	// leaves one version.
	Define(context.Context, *DefineRequest) (*DefineResponse, error)
	// Undefine removes a kind and every version of it, and refuses while
	// any instance is left.
	Undefine(context.Context, *UndefineRequest) (*UndefineResponse, error)
	// GetDefinition is a kind's current shape — one read of an exact key,
	// which is what the head record exists to make possible. With a version
	// it is the shape as it was, which is what a resource pins and what
	// anything reading an older instance has to validate against.
	GetDefinition(context.Context, *GetDefinitionRequest) (*GetDefinitionResponse, error)
	// ListKinds walks every kind that has been defined.
	ListKinds(*ListKindsRequest, grpc.ServerStreamingServer[ListKindsResponse]) error
	// WatchKinds follows what is current. With a kind named, one of them;
	// without, all. A change to a head IS a change to the current
	// definition, so publishing a version that does not become current
	// says nothing here — which is right, because nothing about the kind
	// changed.
	WatchKinds(*WatchKindsRequest, grpc.ServerStreamingServer[WatchKindsResponse]) error
	mustEmbedUnimplementedKernelServiceServer()
}

// UnimplementedKernelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelServiceServer struct{}

func (UnimplementedKernelServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKernelServiceServer) List(*ListRequest, grpc.ServerStreamingServer[ListResponse]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKernelServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedKernelServiceServer) Revision(context.Context, *RevisionRequest) (*RevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Revision not implemented")
}
func (UnimplementedKernelServiceServer) Holders(context.Context, *HoldersRequest) (*HoldersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Holders not implemented")
}
func (UnimplementedKernelServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedKernelServiceServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedKernelServiceServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedKernelServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedKernelServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKernelServiceServer) Define(context.Context, *DefineRequest) (*DefineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Define not implemented")
}
func (UnimplementedKernelServiceServer) Undefine(context.Context, *UndefineRequest) (*UndefineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Undefine not implemented")
}
func (UnimplementedKernelServiceServer) GetDefinition(context.Context, *GetDefinitionRequest) (*GetDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefinition not implemented")
}
func (UnimplementedKernelServiceServer) ListKinds(*ListKindsRequest, grpc.ServerStreamingServer[ListKindsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListKinds not implemented")
}
func (UnimplementedKernelServiceServer) WatchKinds(*WatchKindsRequest, grpc.ServerStreamingServer[WatchKindsResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchKinds not implemented")
}
func (UnimplementedKernelServiceServer) mustEmbedUnimplementedKernelServiceServer() {}
func (UnimplementedKernelServiceServer) testEmbeddedByValue()                       {}

// UnsafeKernelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServiceServer will
// result in compilation errors.
type UnsafeKernelServiceServer interface {
	mustEmbedUnimplementedKernelServiceServer()
}

func RegisterKernelServiceServer(s grpc.ServiceRegistrar, srv KernelServiceServer) {
	// If the following call panics, it indicates UnimplementedKernelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelService_ServiceDesc, srv)
}

func _KernelService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServiceServer).List(m, &grpc.GenericServerStream[ListRequest, ListResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_ListServer = grpc.ServerStreamingServer[ListResponse]

func _KernelService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_WatchServer = grpc.ServerStreamingServer[WatchResponse]

func _KernelService_Revision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Revision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Revision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Revision(ctx, req.(*RevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Holders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoldersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Holders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Holders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Holders(ctx, req.(*HoldersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Define_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Define(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Define_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Define(ctx, req.(*DefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_Undefine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).Undefine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_Undefine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).Undefine(ctx, req.(*UndefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_GetDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GetDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GetDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GetDefinition(ctx, req.(*GetDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ListKinds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListKindsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServiceServer).ListKinds(m, &grpc.GenericServerStream[ListKindsRequest, ListKindsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_ListKindsServer = grpc.ServerStreamingServer[ListKindsResponse]

func _KernelService_WatchKinds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchKindsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelServiceServer).WatchKinds(m, &grpc.GenericServerStream[WatchKindsRequest, WatchKindsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelService_WatchKindsServer = grpc.ServerStreamingServer[WatchKindsResponse]

// KernelService_ServiceDesc is the grpc.ServiceDesc for KernelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KernelService",
	HandlerType: (*KernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KernelService_Get_Handler,
		},
		{
			MethodName: "Revision",
			Handler:    _KernelService_Revision_Handler,
		},
		{
			MethodName: "Holders",
			Handler:    _KernelService_Holders_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _KernelService_Put_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _KernelService_Report_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _KernelService_Claim_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _KernelService_Release_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KernelService_Delete_Handler,
		},
		{
			MethodName: "Define",
			Handler:    _KernelService_Define_Handler,
		},
		{
			MethodName: "Undefine",
			Handler:    _KernelService_Undefine_Handler,
		},
		{
			MethodName: "GetDefinition",
			Handler:    _KernelService_GetDefinition_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _KernelService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _KernelService_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListKinds",
			Handler:       _KernelService_ListKinds_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchKinds",
			Handler:       _KernelService_WatchKinds_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/kernel.proto",
}
