// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/resource.proto

package graphenepbv1

import (
	schemapb "github.com/gopherex/schemapb/go/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_PUT         EventType = 1
	EventType_EVENT_TYPE_DELETE      EventType = 2
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PUT",
		2: "EVENT_TYPE_DELETE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_PUT":         1,
		"EVENT_TYPE_DELETE":      2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_resource_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_v1_resource_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{0}
}

// Key — kind + explicit path. The path shape is per-kind (declared by the
// kind's definition); path segments never contain '/'.
type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Path          []string               `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Key) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Desired/declared VALUES (user intent). No schema here — the shape
	// lives in the kind's definition.
	Spec *schemapb.StructValue `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Observed/outcome VALUES; for system kinds written by system roles
	// only.
	Status *schemapb.StructValue `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Per-resource CAS revision: Put succeeds only when expected_revision
	// matches. Assigned by the store, monotonic per key.
	Revision uint64 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	// Which version of the kind's definition these values conform to.
	DefinitionVersion uint32 `protobuf:"varint,5,opt,name=definition_version,json=definitionVersion,proto3" json:"definition_version,omitempty"`
	// Machine-readable outgoing references — GC reachability roots
	// (blobs and other resources this one keeps alive).
	ResourceRefs  []*Key     `protobuf:"bytes,6,rep,name=resource_refs,json=resourceRefs,proto3" json:"resource_refs,omitempty"`
	BlobRefs      []*BlobRef `protobuf:"bytes,7,rep,name=blob_refs,json=blobRefs,proto3" json:"blob_refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Resource) GetSpec() *schemapb.StructValue {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() *schemapb.StructValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Resource) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Resource) GetDefinitionVersion() uint32 {
	if x != nil {
		return x.DefinitionVersion
	}
	return 0
}

func (x *Resource) GetResourceRefs() []*Key {
	if x != nil {
		return x.ResourceRefs
	}
	return nil
}

func (x *Resource) GetBlobRefs() []*BlobRef {
	if x != nil {
		return x.BlobRefs
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resource.revision is ignored on input; use expected_revision.
	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// CAS guard: current revision of the key, or 0 for "must not exist"
	// (create). Mismatch = ABORTED — the caller re-reads and decides.
	ExpectedRevision uint64 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *PutRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *PutRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new revision of the resource.
	Revision uint64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	// Global store revision of this write (watch cursor space).
	StoreRevision uint64 `protobuf:"varint,2,opt,name=store_revision,json=storeRevision,proto3" json:"store_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *PutResponse) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *PutResponse) GetStoreRevision() uint64 {
	if x != nil {
		return x.StoreRevision
	}
	return 0
}

type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   *Key                   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// CAS guard, same semantics as PutRequest.expected_revision.
	ExpectedRevision uint64 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{7}
}

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Match resources whose path starts with these segments. Empty = all.
	PathPrefix    []string `protobuf:"bytes,2,rep,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	PageSize      uint32   `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string   `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_v1_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{8}
}

func (x *ListRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListRequest) GetPathPrefix() []string {
	if x != nil {
		return x.PathPrefix
	}
	return nil
}

func (x *ListRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_v1_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type WatchRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Kind       string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	PathPrefix []string               `protobuf:"bytes,2,rep,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// Resume cursor in the global revision space: replay events after this
	// revision, then stream live. 0 = current state snapshot first (every
	// matching resource as a PUT), then live.
	FromStoreRevision uint64 `protobuf:"varint,3,opt,name=from_store_revision,json=fromStoreRevision,proto3" json:"from_store_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_v1_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{10}
}

func (x *WatchRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WatchRequest) GetPathPrefix() []string {
	if x != nil {
		return x.PathPrefix
	}
	return nil
}

func (x *WatchRequest) GetFromStoreRevision() uint64 {
	if x != nil {
		return x.FromStoreRevision
	}
	return 0
}

type WatchEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=EventType" json:"type,omitempty"`
	Resource *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Cursor to resume from (WatchRequest.from_store_revision).
	StoreRevision uint64 `protobuf:"varint,3,opt,name=store_revision,json=storeRevision,proto3" json:"store_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_v1_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{11}
}

func (x *WatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *WatchEvent) GetStoreRevision() uint64 {
	if x != nil {
		return x.StoreRevision
	}
	return 0
}

type ResourceDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind name this definition describes: "Secret", "aws.vm", ...
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Monotonic definition version, assigned on Define. Instances pin it
	// in definition_version; evolution/migration is per-kind policy.
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// Shape of the key path: named segments, e.g. tenant/env/workflow/name.
	PathSegments []string `protobuf:"bytes,3,rep,name=path_segments,json=pathSegments,proto3" json:"path_segments,omitempty"`
	// Shape of instances' spec values.
	SpecSchema *schemapb.Schema `protobuf:"bytes,4,opt,name=spec_schema,json=specSchema,proto3" json:"spec_schema,omitempty"`
	// Shape of instances' status values.
	StatusSchema *schemapb.Schema `protobuf:"bytes,5,opt,name=status_schema,json=statusSchema,proto3" json:"status_schema,omitempty"`
	// Optional. Present = the kind is ACTIVE: the control kernel's generic
	// driver watches its instances and schedules executions of these
	// entrypoints (the operator pattern without resident processes).
	// Absent = passive kind: storage, validation, refs — no behavior.
	Controller    *ControllerBinding `protobuf:"bytes,6,opt,name=controller,proto3" json:"controller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceDefinition) Reset() {
	*x = ResourceDefinition{}
	mi := &file_v1_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDefinition) ProtoMessage() {}

func (x *ResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDefinition.ProtoReflect.Descriptor instead.
func (*ResourceDefinition) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceDefinition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceDefinition) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResourceDefinition) GetPathSegments() []string {
	if x != nil {
		return x.PathSegments
	}
	return nil
}

func (x *ResourceDefinition) GetSpecSchema() *schemapb.Schema {
	if x != nil {
		return x.SpecSchema
	}
	return nil
}

func (x *ResourceDefinition) GetStatusSchema() *schemapb.Schema {
	if x != nil {
		return x.StatusSchema
	}
	return nil
}

func (x *ResourceDefinition) GetController() *ControllerBinding {
	if x != nil {
		return x.Controller
	}
	return nil
}

// Controller binding: WHO reconciles instances of the kind. Not a resident
// process — a program entrypoint the driver schedules as a normal
// Execution when reconciliation is due (spec change, declared drift
// re-check, teardown). Built-in kinds have no binding: their controllers
// are compiled into the kernels.
type ControllerBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key of the Program resource carrying the controller entrypoints.
	Program *Key `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	// Reconcile entrypoint: (spec, prev status) → new status (R14).
	ReconcileEntrypoint string `protobuf:"bytes,2,opt,name=reconcile_entrypoint,json=reconcileEntrypoint,proto3" json:"reconcile_entrypoint,omitempty"`
	// Teardown entrypoint: (last status) → gone (R16).
	DestroyEntrypoint string `protobuf:"bytes,3,opt,name=destroy_entrypoint,json=destroyEntrypoint,proto3" json:"destroy_entrypoint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControllerBinding) Reset() {
	*x = ControllerBinding{}
	mi := &file_v1_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerBinding) ProtoMessage() {}

func (x *ControllerBinding) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerBinding.ProtoReflect.Descriptor instead.
func (*ControllerBinding) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{13}
}

func (x *ControllerBinding) GetProgram() *Key {
	if x != nil {
		return x.Program
	}
	return nil
}

func (x *ControllerBinding) GetReconcileEntrypoint() string {
	if x != nil {
		return x.ReconcileEntrypoint
	}
	return ""
}

func (x *ControllerBinding) GetDestroyEntrypoint() string {
	if x != nil {
		return x.DestroyEntrypoint
	}
	return ""
}

type DefineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// definition.version is ignored on input; the server assigns the next.
	Definition    *ResourceDefinition `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefineRequest) Reset() {
	*x = DefineRequest{}
	mi := &file_v1_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefineRequest) ProtoMessage() {}

func (x *DefineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefineRequest.ProtoReflect.Descriptor instead.
func (*DefineRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{14}
}

func (x *DefineRequest) GetDefinition() *ResourceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type DefineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The assigned definition version.
	Version       uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefineResponse) Reset() {
	*x = DefineResponse{}
	mi := &file_v1_resource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefineResponse) ProtoMessage() {}

func (x *DefineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefineResponse.ProtoReflect.Descriptor instead.
func (*DefineResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{15}
}

func (x *DefineResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetDefinitionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// 0 = latest.
	Version       uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionRequest) Reset() {
	*x = GetDefinitionRequest{}
	mi := &file_v1_resource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionRequest) ProtoMessage() {}

func (x *GetDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionRequest.ProtoReflect.Descriptor instead.
func (*GetDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{16}
}

func (x *GetDefinitionRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetDefinitionRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *ResourceDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinitionResponse) Reset() {
	*x = GetDefinitionResponse{}
	mi := &file_v1_resource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinitionResponse) ProtoMessage() {}

func (x *GetDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinitionResponse.ProtoReflect.Descriptor instead.
func (*GetDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{17}
}

func (x *GetDefinitionResponse) GetDefinition() *ResourceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type ListDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsRequest) Reset() {
	*x = ListDefinitionsRequest{}
	mi := &file_v1_resource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsRequest) ProtoMessage() {}

func (x *ListDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{18}
}

func (x *ListDefinitionsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDefinitionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListDefinitionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latest version of every kind.
	Definitions   []*ResourceDefinition `protobuf:"bytes,1,rep,name=definitions,proto3" json:"definitions,omitempty"`
	NextPageToken string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDefinitionsResponse) Reset() {
	*x = ListDefinitionsResponse{}
	mi := &file_v1_resource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDefinitionsResponse) ProtoMessage() {}

func (x *ListDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{19}
}

func (x *ListDefinitionsResponse) GetDefinitions() []*ResourceDefinition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *ListDefinitionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type WatchDefinitionsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromStoreRevision uint64                 `protobuf:"varint,1,opt,name=from_store_revision,json=fromStoreRevision,proto3" json:"from_store_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WatchDefinitionsRequest) Reset() {
	*x = WatchDefinitionsRequest{}
	mi := &file_v1_resource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDefinitionsRequest) ProtoMessage() {}

func (x *WatchDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*WatchDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{20}
}

func (x *WatchDefinitionsRequest) GetFromStoreRevision() uint64 {
	if x != nil {
		return x.FromStoreRevision
	}
	return 0
}

type WatchDefinitionsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Definition    *ResourceDefinition    `protobuf:"bytes,1,opt,name=definition,proto3" json:"definition,omitempty"`
	StoreRevision uint64                 `protobuf:"varint,2,opt,name=store_revision,json=storeRevision,proto3" json:"store_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDefinitionsEvent) Reset() {
	*x = WatchDefinitionsEvent{}
	mi := &file_v1_resource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDefinitionsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDefinitionsEvent) ProtoMessage() {}

func (x *WatchDefinitionsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDefinitionsEvent.ProtoReflect.Descriptor instead.
func (*WatchDefinitionsEvent) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{21}
}

func (x *WatchDefinitionsEvent) GetDefinition() *ResourceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *WatchDefinitionsEvent) GetStoreRevision() uint64 {
	if x != nil {
		return x.StoreRevision
	}
	return 0
}

var File_v1_resource_proto protoreflect.FileDescriptor

const file_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x11v1/resource.proto\x1a\x15schemapb/schema.proto\x1a\x14schemapb/value.proto\x1a\rv1/blob.proto\"-\n" +
	"\x03Key\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x03(\tR\x04path\"\x99\x02\n" +
	"\bResource\x12\x16\n" +
	"\x03key\x18\x01 \x01(\v2\x04.KeyR\x03key\x12)\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x04spec\x12-\n" +
	"\x06status\x18\x03 \x01(\v2\x15.schemapb.StructValueR\x06status\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12-\n" +
	"\x12definition_version\x18\x05 \x01(\rR\x11definitionVersion\x12)\n" +
	"\rresource_refs\x18\x06 \x03(\v2\x04.KeyR\fresourceRefs\x12%\n" +
	"\tblob_refs\x18\a \x03(\v2\b.BlobRefR\bblobRefs\"$\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x03key\x18\x01 \x01(\v2\x04.KeyR\x03key\"4\n" +
	"\vGetResponse\x12%\n" +
	"\bresource\x18\x01 \x01(\v2\t.ResourceR\bresource\"`\n" +
	"\n" +
	"PutRequest\x12%\n" +
	"\bresource\x18\x01 \x01(\v2\t.ResourceR\bresource\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\"P\n" +
	"\vPutResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12%\n" +
	"\x0estore_revision\x18\x02 \x01(\x04R\rstoreRevision\"T\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x03key\x18\x01 \x01(\v2\x04.KeyR\x03key\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\"\x10\n" +
	"\x0eDeleteResponse\"~\n" +
	"\vListRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x03(\tR\n" +
	"pathPrefix\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"_\n" +
	"\fListResponse\x12'\n" +
	"\tresources\x18\x01 \x03(\v2\t.ResourceR\tresources\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"s\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x03(\tR\n" +
	"pathPrefix\x12.\n" +
	"\x13from_store_revision\x18\x03 \x01(\x04R\x11fromStoreRevision\"z\n" +
	"\n" +
	"WatchEvent\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\x0e2\n" +
	".EventTypeR\x04type\x12%\n" +
	"\bresource\x18\x02 \x01(\v2\t.ResourceR\bresource\x12%\n" +
	"\x0estore_revision\x18\x03 \x01(\x04R\rstoreRevision\"\x85\x02\n" +
	"\x12ResourceDefinition\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12#\n" +
	"\rpath_segments\x18\x03 \x03(\tR\fpathSegments\x121\n" +
	"\vspec_schema\x18\x04 \x01(\v2\x10.schemapb.SchemaR\n" +
	"specSchema\x125\n" +
	"\rstatus_schema\x18\x05 \x01(\v2\x10.schemapb.SchemaR\fstatusSchema\x122\n" +
	"\n" +
	"controller\x18\x06 \x01(\v2\x12.ControllerBindingR\n" +
	"controller\"\x95\x01\n" +
	"\x11ControllerBinding\x12\x1e\n" +
	"\aprogram\x18\x01 \x01(\v2\x04.KeyR\aprogram\x121\n" +
	"\x14reconcile_entrypoint\x18\x02 \x01(\tR\x13reconcileEntrypoint\x12-\n" +
	"\x12destroy_entrypoint\x18\x03 \x01(\tR\x11destroyEntrypoint\"D\n" +
	"\rDefineRequest\x123\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x13.ResourceDefinitionR\n" +
	"definition\"*\n" +
	"\x0eDefineResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\"D\n" +
	"\x14GetDefinitionRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\"L\n" +
	"\x15GetDefinitionResponse\x123\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x13.ResourceDefinitionR\n" +
	"definition\"T\n" +
	"\x16ListDefinitionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"x\n" +
	"\x17ListDefinitionsResponse\x125\n" +
	"\vdefinitions\x18\x01 \x03(\v2\x13.ResourceDefinitionR\vdefinitions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"I\n" +
	"\x17WatchDefinitionsRequest\x12.\n" +
	"\x13from_store_revision\x18\x01 \x01(\x04R\x11fromStoreRevision\"s\n" +
	"\x15WatchDefinitionsEvent\x123\n" +
	"\n" +
	"definition\x18\x01 \x01(\v2\x13.ResourceDefinitionR\n" +
	"definition\x12%\n" +
	"\x0estore_revision\x18\x02 \x01(\x04R\rstoreRevision*R\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_PUT\x10\x01\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x022\xc5\x03\n" +
	"\x0fResourceService\x12 \n" +
	"\x03Get\x12\v.GetRequest\x1a\f.GetResponse\x12 \n" +
	"\x03Put\x12\v.PutRequest\x1a\f.PutResponse\x12)\n" +
	"\x06Delete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\x12#\n" +
	"\x04List\x12\f.ListRequest\x1a\r.ListResponse\x12%\n" +
	"\x05Watch\x12\r.WatchRequest\x1a\v.WatchEvent0\x01\x12)\n" +
	"\x06Define\x12\x0e.DefineRequest\x1a\x0f.DefineResponse\x12>\n" +
	"\rGetDefinition\x12\x15.GetDefinitionRequest\x1a\x16.GetDefinitionResponse\x12D\n" +
	"\x0fListDefinitions\x12\x17.ListDefinitionsRequest\x1a\x18.ListDefinitionsResponse\x12F\n" +
	"\x10WatchDefinitions\x12\x18.WatchDefinitionsRequest\x1a\x16.WatchDefinitionsEvent0\x01B3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_resource_proto_rawDescOnce sync.Once
	file_v1_resource_proto_rawDescData []byte
)

func file_v1_resource_proto_rawDescGZIP() []byte {
	file_v1_resource_proto_rawDescOnce.Do(func() {
		file_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_resource_proto_rawDesc), len(file_v1_resource_proto_rawDesc)))
	})
	return file_v1_resource_proto_rawDescData
}

var file_v1_resource_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_v1_resource_proto_goTypes = []any{
	(EventType)(0),                  // 0: EventType
	(*Key)(nil),                     // 1: Key
	(*Resource)(nil),                // 2: Resource
	(*GetRequest)(nil),              // 3: GetRequest
	(*GetResponse)(nil),             // 4: GetResponse
	(*PutRequest)(nil),              // 5: PutRequest
	(*PutResponse)(nil),             // 6: PutResponse
	(*DeleteRequest)(nil),           // 7: DeleteRequest
	(*DeleteResponse)(nil),          // 8: DeleteResponse
	(*ListRequest)(nil),             // 9: ListRequest
	(*ListResponse)(nil),            // 10: ListResponse
	(*WatchRequest)(nil),            // 11: WatchRequest
	(*WatchEvent)(nil),              // 12: WatchEvent
	(*ResourceDefinition)(nil),      // 13: ResourceDefinition
	(*ControllerBinding)(nil),       // 14: ControllerBinding
	(*DefineRequest)(nil),           // 15: DefineRequest
	(*DefineResponse)(nil),          // 16: DefineResponse
	(*GetDefinitionRequest)(nil),    // 17: GetDefinitionRequest
	(*GetDefinitionResponse)(nil),   // 18: GetDefinitionResponse
	(*ListDefinitionsRequest)(nil),  // 19: ListDefinitionsRequest
	(*ListDefinitionsResponse)(nil), // 20: ListDefinitionsResponse
	(*WatchDefinitionsRequest)(nil), // 21: WatchDefinitionsRequest
	(*WatchDefinitionsEvent)(nil),   // 22: WatchDefinitionsEvent
	(*schemapb.StructValue)(nil),    // 23: schemapb.StructValue
	(*BlobRef)(nil),                 // 24: BlobRef
	(*schemapb.Schema)(nil),         // 25: schemapb.Schema
}
var file_v1_resource_proto_depIdxs = []int32{
	1,  // 0: Resource.key:type_name -> Key
	23, // 1: Resource.spec:type_name -> schemapb.StructValue
	23, // 2: Resource.status:type_name -> schemapb.StructValue
	1,  // 3: Resource.resource_refs:type_name -> Key
	24, // 4: Resource.blob_refs:type_name -> BlobRef
	1,  // 5: GetRequest.key:type_name -> Key
	2,  // 6: GetResponse.resource:type_name -> Resource
	2,  // 7: PutRequest.resource:type_name -> Resource
	1,  // 8: DeleteRequest.key:type_name -> Key
	2,  // 9: ListResponse.resources:type_name -> Resource
	0,  // 10: WatchEvent.type:type_name -> EventType
	2,  // 11: WatchEvent.resource:type_name -> Resource
	25, // 12: ResourceDefinition.spec_schema:type_name -> schemapb.Schema
	25, // 13: ResourceDefinition.status_schema:type_name -> schemapb.Schema
	14, // 14: ResourceDefinition.controller:type_name -> ControllerBinding
	1,  // 15: ControllerBinding.program:type_name -> Key
	13, // 16: DefineRequest.definition:type_name -> ResourceDefinition
	13, // 17: GetDefinitionResponse.definition:type_name -> ResourceDefinition
	13, // 18: ListDefinitionsResponse.definitions:type_name -> ResourceDefinition
	13, // 19: WatchDefinitionsEvent.definition:type_name -> ResourceDefinition
	3,  // 20: ResourceService.Get:input_type -> GetRequest
	5,  // 21: ResourceService.Put:input_type -> PutRequest
	7,  // 22: ResourceService.Delete:input_type -> DeleteRequest
	9,  // 23: ResourceService.List:input_type -> ListRequest
	11, // 24: ResourceService.Watch:input_type -> WatchRequest
	15, // 25: ResourceService.Define:input_type -> DefineRequest
	17, // 26: ResourceService.GetDefinition:input_type -> GetDefinitionRequest
	19, // 27: ResourceService.ListDefinitions:input_type -> ListDefinitionsRequest
	21, // 28: ResourceService.WatchDefinitions:input_type -> WatchDefinitionsRequest
	4,  // 29: ResourceService.Get:output_type -> GetResponse
	6,  // 30: ResourceService.Put:output_type -> PutResponse
	8,  // 31: ResourceService.Delete:output_type -> DeleteResponse
	10, // 32: ResourceService.List:output_type -> ListResponse
	12, // 33: ResourceService.Watch:output_type -> WatchEvent
	16, // 34: ResourceService.Define:output_type -> DefineResponse
	18, // 35: ResourceService.GetDefinition:output_type -> GetDefinitionResponse
	20, // 36: ResourceService.ListDefinitions:output_type -> ListDefinitionsResponse
	22, // 37: ResourceService.WatchDefinitions:output_type -> WatchDefinitionsEvent
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_resource_proto_init() }
func file_v1_resource_proto_init() {
	if File_v1_resource_proto != nil {
		return
	}
	file_v1_blob_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_resource_proto_rawDesc), len(file_v1_resource_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_resource_proto_goTypes,
		DependencyIndexes: file_v1_resource_proto_depIdxs,
		EnumInfos:         file_v1_resource_proto_enumTypes,
		MessageInfos:      file_v1_resource_proto_msgTypes,
	}.Build()
	File_v1_resource_proto = out.File
	file_v1_resource_proto_goTypes = nil
	file_v1_resource_proto_depIdxs = nil
}
