// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/resource.proto

package graphenepbv1

import (
	schemapb "github.com/gopherex/schemapb/go/schemapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource is one admitted instance of a kind, as stored.
//
// Four different parties write the fields below, and the split matters
// more than the list does:
//
//	the author   id, spec, finalizers
//	a controller status
//	the kernel   generation, definition_version, deleting
//	the store    neither of its revisions — they are NOT here
//
// The last line is the one worth reading twice. A record does not carry
// the revision it was written at, because a value that can hold a
// revision can hold a stale one: the old code stored it inside and had to
// scrub two fields before every write, and the bug was always a forgotten
// scrub rather than a wrong value. The store keeps its stamps beside the
// value, where they cannot be copied into it.
//
// On the Go side this mirrors resource.Snapshot field for field, so the
// converter is a field-for-field map with nothing clever in it. A field
// added to one and not the other is caught by a canary that stops
// compiling.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is which resource this is.
	Id *Id `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Spec is what the author asked for. It is validated against the kind's
	// spec schema at admission and never again — the version it was
	// admitted under is pinned below, and re-checking a v1 value against a
	// v3 schema would refuse what was correct when written.
	Spec *schemapb.StructValue `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Status is what the controller reported back, absent until it reports
	// anything.
	//
	// Absent and empty are different answers: absent is "nobody has looked
	// at this yet", empty is "somebody looked and found nothing to say".
	Status *schemapb.StructValue `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Finalizers are the claims that must be released before this may
	// actually be removed. While one is present the record is marked for
	// deletion and kept, so whoever put it there gets to clean up first.
	Finalizers []string `protobuf:"bytes,5,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	// Generation counts INTENT, not writes: it moves when the spec moves
	// and at no other time.
	//
	// This is what lets a controller ignore the echo of its own status
	// write. The revision moves on every write including that one; this
	// does not, so a controller that records the generation it acted on can
	// compare and go back to sleep. Without it, "react to changes" is an
	// infinite loop.
	Generation uint64 `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	// DefinitionVersion is the version of the kind's definition this was
	// admitted against.
	//
	// Pinned rather than looked up, because the definition may have moved
	// on. A resource admitted under v1 is a v1 resource until something
	// rewrites it, and anything reading it has to know which shape it is
	// reading.
	DefinitionVersion uint32 `protobuf:"varint,7,opt,name=definition_version,json=definitionVersion,proto3" json:"definition_version,omitempty"`
	// Deleting marks a record that has been asked to go away and is waiting
	// on its finalizers. It still exists and can still be read; what it can
	// no longer do is change its spec, because the finalizers are running
	// against the spec it had.
	Deleting bool `protobuf:"varint,8,opt,name=deleting,proto3" json:"deleting,omitempty"`
	// Author is who made the last write to this record, whichever half it
	// touched.
	//
	// Set by the kernel from the credential the call arrived with, and by
	// nothing else: a value a caller could send would be a value a caller
	// could choose, which would make it worth less than nothing.
	//
	// Empty means the kernel itself — a store being bootstrapped, a kernel
	// writing down that it exists. Those writes have no caller, and
	// inventing a name for one would be worse than saying there was none.
	//
	// It grants nothing and is read by nobody deciding anything. It is what
	// makes a decision somebody else made afterwards-explicable.
	Author        string `protobuf:"bytes,9,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Resource) GetSpec() *schemapb.StructValue {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() *schemapb.StructValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Resource) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *Resource) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Resource) GetDefinitionVersion() uint32 {
	if x != nil {
		return x.DefinitionVersion
	}
	return 0
}

func (x *Resource) GetDeleting() bool {
	if x != nil {
		return x.Deleting
	}
	return false
}

func (x *Resource) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

var File_v1_resource_proto protoreflect.FileDescriptor

const file_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x11v1/resource.proto\x1a\x14schemapb/value.proto\x1a\vv1/id.proto\"\xa9\x02\n" +
	"\bResource\x12\x13\n" +
	"\x02id\x18\x01 \x01(\v2\x03.IdR\x02id\x12)\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.schemapb.StructValueR\x04spec\x12-\n" +
	"\x06status\x18\x03 \x01(\v2\x15.schemapb.StructValueR\x06status\x12\x1e\n" +
	"\n" +
	"finalizers\x18\x05 \x03(\tR\n" +
	"finalizers\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x04R\n" +
	"generation\x12-\n" +
	"\x12definition_version\x18\a \x01(\rR\x11definitionVersion\x12\x1a\n" +
	"\bdeleting\x18\b \x01(\bR\bdeleting\x12\x16\n" +
	"\x06author\x18\t \x01(\tR\x06authorJ\x04\b\x04\x10\x05R\x05ownerB3Z1github.com/graphene-ci/graphenepb/v1;graphenepbv1b\x06proto3"

var (
	file_v1_resource_proto_rawDescOnce sync.Once
	file_v1_resource_proto_rawDescData []byte
)

func file_v1_resource_proto_rawDescGZIP() []byte {
	file_v1_resource_proto_rawDescOnce.Do(func() {
		file_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_resource_proto_rawDesc), len(file_v1_resource_proto_rawDesc)))
	})
	return file_v1_resource_proto_rawDescData
}

var file_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_resource_proto_goTypes = []any{
	(*Resource)(nil),             // 0: Resource
	(*Id)(nil),                   // 1: Id
	(*schemapb.StructValue)(nil), // 2: schemapb.StructValue
}
var file_v1_resource_proto_depIdxs = []int32{
	1, // 0: Resource.id:type_name -> Id
	2, // 1: Resource.spec:type_name -> schemapb.StructValue
	2, // 2: Resource.status:type_name -> schemapb.StructValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_resource_proto_init() }
func file_v1_resource_proto_init() {
	if File_v1_resource_proto != nil {
		return
	}
	file_v1_id_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_resource_proto_rawDesc), len(file_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_resource_proto_goTypes,
		DependencyIndexes: file_v1_resource_proto_depIdxs,
		MessageInfos:      file_v1_resource_proto_msgTypes,
	}.Build()
	File_v1_resource_proto = out.File
	file_v1_resource_proto_goTypes = nil
	file_v1_resource_proto_depIdxs = nil
}
