// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/agent/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Connect_FullMethodName             = "/graphene.v1.agent.AgentService/Connect"
	AgentService_DownloadArtifact_FullMethodName    = "/graphene.v1.agent.AgentService/DownloadArtifact"
	AgentService_QueryArtifactUpload_FullMethodName = "/graphene.v1.agent.AgentService/QueryArtifactUpload"
	AgentService_UploadArtifact_FullMethodName      = "/graphene.v1.agent.AgentService/UploadArtifact"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService exposes the server-side RPCs used by machine agents.
// Every RPC is initiated by the agent because the agent is always the client.
type AgentServiceClient interface {
	// Connect creates the long-lived control channel for one agent installation.
	// The first ConnectRequest on every connection must contain Hello. Independent
	// operation failures are reported through OperationFailed and do not close
	// this stream.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error)
	// DownloadArtifact streams an existing artifact from the server to an agent
	// that was previously given a matching PutArtifact instruction.
	DownloadArtifact(ctx context.Context, in *DownloadArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadArtifactResponse], error)
	// QueryArtifactUpload returns the durable progress of an upload attempt so
	// the agent can verify the retained prefix and resume without resending it.
	QueryArtifactUpload(ctx context.Context, in *QueryArtifactUploadRequest, opts ...grpc.CallOption) (*QueryArtifactUploadResponse, error)
	// UploadArtifact streams a machine-local file from the agent to the server.
	// Frames must follow begin, ordered chunks, finish. The result contains the
	// canonical metadata verified by the server.
	UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadArtifactRequest, UploadArtifactResponse], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.BidiStreamingClient[ConnectRequest, ConnectResponse]

func (c *agentServiceClient) DownloadArtifact(ctx context.Context, in *DownloadArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_DownloadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadArtifactRequest, DownloadArtifactResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_DownloadArtifactClient = grpc.ServerStreamingClient[DownloadArtifactResponse]

func (c *agentServiceClient) QueryArtifactUpload(ctx context.Context, in *QueryArtifactUploadRequest, opts ...grpc.CallOption) (*QueryArtifactUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryArtifactUploadResponse)
	err := c.cc.Invoke(ctx, AgentService_QueryArtifactUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadArtifactRequest, UploadArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_UploadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadArtifactRequest, UploadArtifactResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_UploadArtifactClient = grpc.ClientStreamingClient[UploadArtifactRequest, UploadArtifactResponse]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService exposes the server-side RPCs used by machine agents.
// Every RPC is initiated by the agent because the agent is always the client.
type AgentServiceServer interface {
	// Connect creates the long-lived control channel for one agent installation.
	// The first ConnectRequest on every connection must contain Hello. Independent
	// operation failures are reported through OperationFailed and do not close
	// this stream.
	Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error
	// DownloadArtifact streams an existing artifact from the server to an agent
	// that was previously given a matching PutArtifact instruction.
	DownloadArtifact(*DownloadArtifactRequest, grpc.ServerStreamingServer[DownloadArtifactResponse]) error
	// QueryArtifactUpload returns the durable progress of an upload attempt so
	// the agent can verify the retained prefix and resume without resending it.
	QueryArtifactUpload(context.Context, *QueryArtifactUploadRequest) (*QueryArtifactUploadResponse, error)
	// UploadArtifact streams a machine-local file from the agent to the server.
	// Frames must follow begin, ordered chunks, finish. The result contains the
	// canonical metadata verified by the server.
	UploadArtifact(grpc.ClientStreamingServer[UploadArtifactRequest, UploadArtifactResponse]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) DownloadArtifact(*DownloadArtifactRequest, grpc.ServerStreamingServer[DownloadArtifactResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadArtifact not implemented")
}
func (UnimplementedAgentServiceServer) QueryArtifactUpload(context.Context, *QueryArtifactUploadRequest) (*QueryArtifactUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryArtifactUpload not implemented")
}
func (UnimplementedAgentServiceServer) UploadArtifact(grpc.ClientStreamingServer[UploadArtifactRequest, UploadArtifactResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadArtifact not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&grpc.GenericServerStream[ConnectRequest, ConnectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.BidiStreamingServer[ConnectRequest, ConnectResponse]

func _AgentService_DownloadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).DownloadArtifact(m, &grpc.GenericServerStream[DownloadArtifactRequest, DownloadArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_DownloadArtifactServer = grpc.ServerStreamingServer[DownloadArtifactResponse]

func _AgentService_QueryArtifactUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArtifactUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).QueryArtifactUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_QueryArtifactUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).QueryArtifactUpload(ctx, req.(*QueryArtifactUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UploadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).UploadArtifact(&grpc.GenericServerStream[UploadArtifactRequest, UploadArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_UploadArtifactServer = grpc.ClientStreamingServer[UploadArtifactRequest, UploadArtifactResponse]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.v1.agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryArtifactUpload",
			Handler:    _AgentService_QueryArtifactUpload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadArtifact",
			Handler:       _AgentService_DownloadArtifact_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadArtifact",
			Handler:       _AgentService_UploadArtifact_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "v1/agent/agent.proto",
}
