// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/agent/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Capability identifies an operation or transport mode supported by an agent.
type Capability int32

const (
	// CAPABILITY_UNSPECIFIED is the protobuf zero value and is not a capability.
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	// CAPABILITY_COMMAND means the agent can execute non-interactive commands.
	Capability_CAPABILITY_COMMAND Capability = 1
	// CAPABILITY_TERMINAL means the agent can allocate and control a PTY.
	Capability_CAPABILITY_TERMINAL Capability = 2
	// CAPABILITY_PUT_ARTIFACT means the agent can place server artifacts locally.
	Capability_CAPABILITY_PUT_ARTIFACT Capability = 3
	// CAPABILITY_COLLECT_ARTIFACT means the agent can upload local files as
	// artifacts.
	Capability_CAPABILITY_COLLECT_ARTIFACT Capability = 4
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_COMMAND",
		2: "CAPABILITY_TERMINAL",
		3: "CAPABILITY_PUT_ARTIFACT",
		4: "CAPABILITY_COLLECT_ARTIFACT",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":      0,
		"CAPABILITY_COMMAND":          1,
		"CAPABILITY_TERMINAL":         2,
		"CAPABILITY_PUT_ARTIFACT":     3,
		"CAPABILITY_COLLECT_ARTIFACT": 4,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_agent_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_v1_agent_agent_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{0}
}

// OutputOverflowPolicy selects bounded-buffer behavior under backpressure.
type OutputOverflowPolicy int32

const (
	// OUTPUT_OVERFLOW_POLICY_UNSPECIFIED selects the canonical
	// OUTPUT_OVERFLOW_POLICY_DROP_OLDEST behavior.
	OutputOverflowPolicy_OUTPUT_OVERFLOW_POLICY_UNSPECIFIED OutputOverflowPolicy = 0
	// OUTPUT_OVERFLOW_POLICY_DROP_OLDEST discards the oldest unsent bytes and
	// retains the most recent output, which normally contains failure details.
	OutputOverflowPolicy_OUTPUT_OVERFLOW_POLICY_DROP_OLDEST OutputOverflowPolicy = 1
	// OUTPUT_OVERFLOW_POLICY_DROP_NEWEST preserves already buffered output and
	// discards newly read bytes until capacity becomes available.
	OutputOverflowPolicy_OUTPUT_OVERFLOW_POLICY_DROP_NEWEST OutputOverflowPolicy = 2
)

// Enum value maps for OutputOverflowPolicy.
var (
	OutputOverflowPolicy_name = map[int32]string{
		0: "OUTPUT_OVERFLOW_POLICY_UNSPECIFIED",
		1: "OUTPUT_OVERFLOW_POLICY_DROP_OLDEST",
		2: "OUTPUT_OVERFLOW_POLICY_DROP_NEWEST",
	}
	OutputOverflowPolicy_value = map[string]int32{
		"OUTPUT_OVERFLOW_POLICY_UNSPECIFIED": 0,
		"OUTPUT_OVERFLOW_POLICY_DROP_OLDEST": 1,
		"OUTPUT_OVERFLOW_POLICY_DROP_NEWEST": 2,
	}
)

func (x OutputOverflowPolicy) Enum() *OutputOverflowPolicy {
	p := new(OutputOverflowPolicy)
	*p = x
	return p
}

func (x OutputOverflowPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputOverflowPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_agent_proto_enumTypes[1].Descriptor()
}

func (OutputOverflowPolicy) Type() protoreflect.EnumType {
	return &file_v1_agent_agent_proto_enumTypes[1]
}

func (x OutputOverflowPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputOverflowPolicy.Descriptor instead.
func (OutputOverflowPolicy) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{1}
}

// Signal is the portable subset of process signals supported by the contract.
type Signal int32

const (
	// SIGNAL_UNSPECIFIED is the protobuf zero value and must be rejected.
	Signal_SIGNAL_UNSPECIFIED Signal = 0
	// SIGNAL_INTERRUPT requests an interactive interruption such as SIGINT.
	Signal_SIGNAL_INTERRUPT Signal = 1
	// SIGNAL_TERMINATE requests graceful termination such as SIGTERM.
	Signal_SIGNAL_TERMINATE Signal = 2
	// SIGNAL_KILL requests immediate forced termination such as SIGKILL.
	Signal_SIGNAL_KILL Signal = 3
)

// Enum value maps for Signal.
var (
	Signal_name = map[int32]string{
		0: "SIGNAL_UNSPECIFIED",
		1: "SIGNAL_INTERRUPT",
		2: "SIGNAL_TERMINATE",
		3: "SIGNAL_KILL",
	}
	Signal_value = map[string]int32{
		"SIGNAL_UNSPECIFIED": 0,
		"SIGNAL_INTERRUPT":   1,
		"SIGNAL_TERMINATE":   2,
		"SIGNAL_KILL":        3,
	}
)

func (x Signal) Enum() *Signal {
	p := new(Signal)
	*p = x
	return p
}

func (x Signal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Signal) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_agent_proto_enumTypes[2].Descriptor()
}

func (Signal) Type() protoreflect.EnumType {
	return &file_v1_agent_agent_proto_enumTypes[2]
}

func (x Signal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Signal.Descriptor instead.
func (Signal) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{2}
}

// OutputStream identifies which command output stream produced a data block.
type OutputStream int32

const (
	// OUTPUT_STREAM_UNSPECIFIED is the protobuf zero value and must be rejected.
	OutputStream_OUTPUT_STREAM_UNSPECIFIED OutputStream = 0
	// OUTPUT_STREAM_STDOUT identifies standard output in non-terminal mode.
	OutputStream_OUTPUT_STREAM_STDOUT OutputStream = 1
	// OUTPUT_STREAM_STDERR identifies standard error in non-terminal mode.
	OutputStream_OUTPUT_STREAM_STDERR OutputStream = 2
	// OUTPUT_STREAM_TERMINAL identifies the merged PTY stream in terminal mode.
	OutputStream_OUTPUT_STREAM_TERMINAL OutputStream = 3
)

// Enum value maps for OutputStream.
var (
	OutputStream_name = map[int32]string{
		0: "OUTPUT_STREAM_UNSPECIFIED",
		1: "OUTPUT_STREAM_STDOUT",
		2: "OUTPUT_STREAM_STDERR",
		3: "OUTPUT_STREAM_TERMINAL",
	}
	OutputStream_value = map[string]int32{
		"OUTPUT_STREAM_UNSPECIFIED": 0,
		"OUTPUT_STREAM_STDOUT":      1,
		"OUTPUT_STREAM_STDERR":      2,
		"OUTPUT_STREAM_TERMINAL":    3,
	}
)

func (x OutputStream) Enum() *OutputStream {
	p := new(OutputStream)
	*p = x
	return p
}

func (x OutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_agent_proto_enumTypes[3].Descriptor()
}

func (OutputStream) Type() protoreflect.EnumType {
	return &file_v1_agent_agent_proto_enumTypes[3]
}

func (x OutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputStream.Descriptor instead.
func (OutputStream) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{3}
}

// ErrorCode classifies operation failures independently of gRPC transport errors.
type ErrorCode int32

const (
	// ERROR_CODE_UNSPECIFIED is the protobuf zero value and must not be emitted.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// ERROR_CODE_INVALID_ARGUMENT means the instruction payload is invalid.
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT ErrorCode = 1
	// ERROR_CODE_NOT_FOUND means a requested path or artifact does not exist.
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 2
	// ERROR_CODE_ALREADY_EXISTS means overwrite was forbidden for an existing
	// destination or immutable artifact.
	ErrorCode_ERROR_CODE_ALREADY_EXISTS ErrorCode = 3
	// ERROR_CODE_PERMISSION_DENIED means authorization or local access failed.
	ErrorCode_ERROR_CODE_PERMISSION_DENIED ErrorCode = 4
	// ERROR_CODE_IO means a local filesystem or artifact transport operation
	// failed.
	ErrorCode_ERROR_CODE_IO ErrorCode = 5
	// ERROR_CODE_START_FAILED means the requested command could not be started.
	ErrorCode_ERROR_CODE_START_FAILED ErrorCode = 6
	// ERROR_CODE_CHECKSUM_MISMATCH means received bytes did not match SHA-256.
	ErrorCode_ERROR_CODE_CHECKSUM_MISMATCH ErrorCode = 7
	// ERROR_CODE_CANCELED means the operation ended due to CancelOperation.
	ErrorCode_ERROR_CODE_CANCELED ErrorCode = 8
	// ERROR_CODE_INTERNAL means the agent could not classify an internal failure
	// more precisely.
	ErrorCode_ERROR_CODE_INTERNAL ErrorCode = 9
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_ALREADY_EXISTS",
		4: "ERROR_CODE_PERMISSION_DENIED",
		5: "ERROR_CODE_IO",
		6: "ERROR_CODE_START_FAILED",
		7: "ERROR_CODE_CHECKSUM_MISMATCH",
		8: "ERROR_CODE_CANCELED",
		9: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":       0,
		"ERROR_CODE_INVALID_ARGUMENT":  1,
		"ERROR_CODE_NOT_FOUND":         2,
		"ERROR_CODE_ALREADY_EXISTS":    3,
		"ERROR_CODE_PERMISSION_DENIED": 4,
		"ERROR_CODE_IO":                5,
		"ERROR_CODE_START_FAILED":      6,
		"ERROR_CODE_CHECKSUM_MISMATCH": 7,
		"ERROR_CODE_CANCELED":          8,
		"ERROR_CODE_INTERNAL":          9,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_agent_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_v1_agent_agent_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{4}
}

// InstallationId identifies one concrete installation of an agent.
type InstallationId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value is a non-empty opaque identifier generated when the agent is
	// installed and changed when it is reinstalled.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallationId) Reset() {
	*x = InstallationId{}
	mi := &file_v1_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallationId) ProtoMessage() {}

func (x *InstallationId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallationId.ProtoReflect.Descriptor instead.
func (*InstallationId) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *InstallationId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// InstructionId identifies one server instruction within an installation.
type InstructionId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value is a non-empty opaque identifier allocated by the server and kept
	// stable for every message belonging to the instruction.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructionId) Reset() {
	*x = InstructionId{}
	mi := &file_v1_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructionId) ProtoMessage() {}

func (x *InstructionId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructionId.ProtoReflect.Descriptor instead.
func (*InstructionId) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *InstructionId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ArtifactId identifies one immutable artifact record.
type ArtifactId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value is a non-empty opaque identifier allocated and persisted by the
	// server before the corresponding instruction is delivered.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactId) Reset() {
	*x = ArtifactId{}
	mi := &file_v1_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactId) ProtoMessage() {}

func (x *ArtifactId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactId.ProtoReflect.Descriptor instead.
func (*ArtifactId) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// ProcessId identifies a process only on the machine where the agent runs.
type ProcessId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value is the operating-system process identifier reported by the agent.
	// Zero means that no meaningful process identifier is available.
	Value         uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessId) Reset() {
	*x = ProcessId{}
	mi := &file_v1_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessId) ProtoMessage() {}

func (x *ProcessId) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessId.ProtoReflect.Descriptor instead.
func (*ProcessId) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessId) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// ConnectRequest is one control-plane event sent from the agent to the server.
type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstructionId correlates an operation event with ConnectResponse.id. It is
	// absent for connection-level Hello, Heartbeat, and Pong events.
	InstructionId *InstructionId `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Event contains exactly one event payload.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*ConnectRequest_Hello
	//	*ConnectRequest_Heartbeat
	//	*ConnectRequest_CommandStarted
	//	*ConnectRequest_CommandOutput
	//	*ConnectRequest_CommandExited
	//	*ConnectRequest_ArtifactPlaced
	//	*ConnectRequest_OperationFailed
	//	*ConnectRequest_Pong
	Event         isConnectRequest_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_v1_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectRequest) GetInstructionId() *InstructionId {
	if x != nil {
		return x.InstructionId
	}
	return nil
}

func (x *ConnectRequest) GetEvent() isConnectRequest_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ConnectRequest) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ConnectRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConnectRequest) GetCommandStarted() *CommandStarted {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_CommandStarted); ok {
			return x.CommandStarted
		}
	}
	return nil
}

func (x *ConnectRequest) GetCommandOutput() *CommandOutput {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_CommandOutput); ok {
			return x.CommandOutput
		}
	}
	return nil
}

func (x *ConnectRequest) GetCommandExited() *CommandExited {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_CommandExited); ok {
			return x.CommandExited
		}
	}
	return nil
}

func (x *ConnectRequest) GetArtifactPlaced() *ArtifactPlaced {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_ArtifactPlaced); ok {
			return x.ArtifactPlaced
		}
	}
	return nil
}

func (x *ConnectRequest) GetOperationFailed() *OperationFailed {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_OperationFailed); ok {
			return x.OperationFailed
		}
	}
	return nil
}

func (x *ConnectRequest) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Event.(*ConnectRequest_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isConnectRequest_Event interface {
	isConnectRequest_Event()
}

type ConnectRequest_Hello struct {
	// Hello introduces the installation and must be the first event on Connect.
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ConnectRequest_Heartbeat struct {
	// Heartbeat reports liveness and the instructions still active locally.
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type ConnectRequest_CommandStarted struct {
	// CommandStarted reports that a requested command was successfully started.
	CommandStarted *CommandStarted `protobuf:"bytes,12,opt,name=command_started,json=commandStarted,proto3,oneof"`
}

type ConnectRequest_CommandOutput struct {
	// CommandOutput carries one ordered block of command output.
	CommandOutput *CommandOutput `protobuf:"bytes,13,opt,name=command_output,json=commandOutput,proto3,oneof"`
}

type ConnectRequest_CommandExited struct {
	// CommandExited is the terminal result of a command that was started.
	CommandExited *CommandExited `protobuf:"bytes,14,opt,name=command_exited,json=commandExited,proto3,oneof"`
}

type ConnectRequest_ArtifactPlaced struct {
	// ArtifactPlaced confirms that PutArtifact was verified and committed.
	ArtifactPlaced *ArtifactPlaced `protobuf:"bytes,15,opt,name=artifact_placed,json=artifactPlaced,proto3,oneof"`
}

type ConnectRequest_OperationFailed struct {
	// OperationFailed reports a failed or canceled correlated operation.
	OperationFailed *OperationFailed `protobuf:"bytes,16,opt,name=operation_failed,json=operationFailed,proto3,oneof"`
}

type ConnectRequest_Pong struct {
	// Pong answers a server Ping and proves that the control stream is usable.
	Pong *Pong `protobuf:"bytes,17,opt,name=pong,proto3,oneof"`
}

func (*ConnectRequest_Hello) isConnectRequest_Event() {}

func (*ConnectRequest_Heartbeat) isConnectRequest_Event() {}

func (*ConnectRequest_CommandStarted) isConnectRequest_Event() {}

func (*ConnectRequest_CommandOutput) isConnectRequest_Event() {}

func (*ConnectRequest_CommandExited) isConnectRequest_Event() {}

func (*ConnectRequest_ArtifactPlaced) isConnectRequest_Event() {}

func (*ConnectRequest_OperationFailed) isConnectRequest_Event() {}

func (*ConnectRequest_Pong) isConnectRequest_Event() {}

// ConnectResponse is one control-plane request sent from the server to the agent.
type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id identifies this operation and correlates every later event or control
	// message belonging to it.
	Id *InstructionId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Instruction contains exactly one requested action.
	//
	// Types that are valid to be assigned to Instruction:
	//
	//	*ConnectResponse_RunCommand
	//	*ConnectResponse_CommandInput
	//	*ConnectResponse_ResizeTerminal
	//	*ConnectResponse_SignalCommand
	//	*ConnectResponse_PutArtifact
	//	*ConnectResponse_CancelOperation
	//	*ConnectResponse_Ping
	//	*ConnectResponse_CollectArtifact
	Instruction   isConnectResponse_Instruction `protobuf_oneof:"instruction"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_v1_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectResponse) GetId() *InstructionId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ConnectResponse) GetInstruction() isConnectResponse_Instruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *ConnectResponse) GetRunCommand() *RunCommand {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_RunCommand); ok {
			return x.RunCommand
		}
	}
	return nil
}

func (x *ConnectResponse) GetCommandInput() *CommandInput {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_CommandInput); ok {
			return x.CommandInput
		}
	}
	return nil
}

func (x *ConnectResponse) GetResizeTerminal() *ResizeTerminal {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_ResizeTerminal); ok {
			return x.ResizeTerminal
		}
	}
	return nil
}

func (x *ConnectResponse) GetSignalCommand() *SignalCommand {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_SignalCommand); ok {
			return x.SignalCommand
		}
	}
	return nil
}

func (x *ConnectResponse) GetPutArtifact() *PutArtifact {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_PutArtifact); ok {
			return x.PutArtifact
		}
	}
	return nil
}

func (x *ConnectResponse) GetCancelOperation() *CancelOperation {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_CancelOperation); ok {
			return x.CancelOperation
		}
	}
	return nil
}

func (x *ConnectResponse) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ConnectResponse) GetCollectArtifact() *CollectArtifact {
	if x != nil {
		if x, ok := x.Instruction.(*ConnectResponse_CollectArtifact); ok {
			return x.CollectArtifact
		}
	}
	return nil
}

type isConnectResponse_Instruction interface {
	isConnectResponse_Instruction()
}

type ConnectResponse_RunCommand struct {
	// RunCommand starts a new shell command.
	RunCommand *RunCommand `protobuf:"bytes,10,opt,name=run_command,json=runCommand,proto3,oneof"`
}

type ConnectResponse_CommandInput struct {
	// CommandInput writes bytes to the stdin of a running command.
	CommandInput *CommandInput `protobuf:"bytes,11,opt,name=command_input,json=commandInput,proto3,oneof"`
}

type ConnectResponse_ResizeTerminal struct {
	// ResizeTerminal changes the PTY dimensions of a running command.
	ResizeTerminal *ResizeTerminal `protobuf:"bytes,12,opt,name=resize_terminal,json=resizeTerminal,proto3,oneof"`
}

type ConnectResponse_SignalCommand struct {
	// SignalCommand sends an operating-system signal to a running command.
	SignalCommand *SignalCommand `protobuf:"bytes,13,opt,name=signal_command,json=signalCommand,proto3,oneof"`
}

type ConnectResponse_PutArtifact struct {
	// PutArtifact places an existing server artifact on the machine.
	PutArtifact *PutArtifact `protobuf:"bytes,14,opt,name=put_artifact,json=putArtifact,proto3,oneof"`
}

type ConnectResponse_CancelOperation struct {
	// CancelOperation requests cancellation of the correlated active operation.
	CancelOperation *CancelOperation `protobuf:"bytes,15,opt,name=cancel_operation,json=cancelOperation,proto3,oneof"`
}

type ConnectResponse_Ping struct {
	// Ping checks whether the agent control stream is responsive.
	Ping *Ping `protobuf:"bytes,16,opt,name=ping,proto3,oneof"`
}

type ConnectResponse_CollectArtifact struct {
	// CollectArtifact stores a machine-local file as a server artifact.
	CollectArtifact *CollectArtifact `protobuf:"bytes,17,opt,name=collect_artifact,json=collectArtifact,proto3,oneof"`
}

func (*ConnectResponse_RunCommand) isConnectResponse_Instruction() {}

func (*ConnectResponse_CommandInput) isConnectResponse_Instruction() {}

func (*ConnectResponse_ResizeTerminal) isConnectResponse_Instruction() {}

func (*ConnectResponse_SignalCommand) isConnectResponse_Instruction() {}

func (*ConnectResponse_PutArtifact) isConnectResponse_Instruction() {}

func (*ConnectResponse_CancelOperation) isConnectResponse_Instruction() {}

func (*ConnectResponse_Ping) isConnectResponse_Instruction() {}

func (*ConnectResponse_CollectArtifact) isConnectResponse_Instruction() {}

// Hello describes an agent installation when it opens Connect.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstallationId identifies the installation opening this connection.
	InstallationId *InstallationId `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	// ProtocolVersion identifies the agent contract version implemented by the
	// client and is used for compatibility checks before instructions are sent.
	ProtocolVersion string `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Hostname is the machine hostname observed by the agent.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// OperatingSystem is the operating-system name reported by the agent.
	OperatingSystem string `protobuf:"bytes,4,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`
	// Architecture is the machine architecture reported by the agent.
	Architecture string `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Capabilities lists the optional operations supported by this agent build.
	Capabilities  []Capability `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=graphene.v1.agent.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_v1_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Hello) GetInstallationId() *InstallationId {
	if x != nil {
		return x.InstallationId
	}
	return nil
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *Hello) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Hello) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Heartbeat reports agent liveness and work that survived a reconnect.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ActiveInstructionIds contains every instruction still running locally.
	// The server must not redeliver an instruction present in this collection.
	ActiveInstructionIds []*InstructionId `protobuf:"bytes,1,rep,name=active_instruction_ids,json=activeInstructionIds,proto3" json:"active_instruction_ids,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_v1_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetActiveInstructionIds() []*InstructionId {
	if x != nil {
		return x.ActiveInstructionIds
	}
	return nil
}

// RunCommand asks the agent to execute the exact shell text supplied by a user.
type RunCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command is passed unchanged to the machine's configured shell. The server
	// must not parse, quote, escape, or rewrite it.
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// WorkingDirectory is the directory in which the shell process starts. An
	// empty value selects the agent's configured default directory.
	WorkingDirectory string `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	// Environment contains variables added to or replacing the agent's default
	// process environment according to agent policy.
	Environment map[string]string `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timeout bounds the command runtime. A zero duration selects the agent's
	// configured default timeout.
	Timeout *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Terminal requests a PTY. When false, stdout and stderr remain separate.
	Terminal bool `protobuf:"varint,5,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// TerminalSize is the initial PTY size. It is ignored when terminal is false.
	TerminalSize *TerminalSize `protobuf:"bytes,6,opt,name=terminal_size,json=terminalSize,proto3" json:"terminal_size,omitempty"`
	// Output controls batching, memory bounds, total streamed volume, and the
	// behavior used when a slow server fills the pending-output buffer.
	Output        *OutputPolicy `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommand) Reset() {
	*x = RunCommand{}
	mi := &file_v1_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommand) ProtoMessage() {}

func (x *RunCommand) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommand.ProtoReflect.Descriptor instead.
func (*RunCommand) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RunCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommand) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *RunCommand) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *RunCommand) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RunCommand) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *RunCommand) GetTerminalSize() *TerminalSize {
	if x != nil {
		return x.TerminalSize
	}
	return nil
}

func (x *RunCommand) GetOutput() *OutputPolicy {
	if x != nil {
		return x.Output
	}
	return nil
}

// OutputPolicy bounds and batches command output sent through Connect.
type OutputPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MaxFrameBytes is the largest CommandOutput.data payload the agent sends.
	// Zero selects the canonical default of 64 KiB.
	MaxFrameBytes uint32 `protobuf:"varint,1,opt,name=max_frame_bytes,json=maxFrameBytes,proto3" json:"max_frame_bytes,omitempty"`
	// FlushInterval is the longest a non-empty partial frame waits before being
	// sent. Zero selects the canonical default of 100 milliseconds.
	FlushInterval *durationpb.Duration `protobuf:"bytes,2,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	// MaxPendingBytes bounds output waiting in agent memory for this command.
	// Zero selects the canonical default of 1 MiB.
	MaxPendingBytes uint64 `protobuf:"varint,3,opt,name=max_pending_bytes,json=maxPendingBytes,proto3" json:"max_pending_bytes,omitempty"`
	// MaxInlineBytes bounds the total output bytes sent through Connect for this
	// command. Zero selects the canonical default of 4 MiB. After the limit is
	// reached the agent keeps draining the command and accounts further bytes as
	// dropped.
	MaxInlineBytes uint64 `protobuf:"varint,4,opt,name=max_inline_bytes,json=maxInlineBytes,proto3" json:"max_inline_bytes,omitempty"`
	// Overflow selects which unsent data is discarded when max_pending_bytes is
	// reached.
	Overflow      OutputOverflowPolicy `protobuf:"varint,5,opt,name=overflow,proto3,enum=graphene.v1.agent.OutputOverflowPolicy" json:"overflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputPolicy) Reset() {
	*x = OutputPolicy{}
	mi := &file_v1_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPolicy) ProtoMessage() {}

func (x *OutputPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPolicy.ProtoReflect.Descriptor instead.
func (*OutputPolicy) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *OutputPolicy) GetMaxFrameBytes() uint32 {
	if x != nil {
		return x.MaxFrameBytes
	}
	return 0
}

func (x *OutputPolicy) GetFlushInterval() *durationpb.Duration {
	if x != nil {
		return x.FlushInterval
	}
	return nil
}

func (x *OutputPolicy) GetMaxPendingBytes() uint64 {
	if x != nil {
		return x.MaxPendingBytes
	}
	return 0
}

func (x *OutputPolicy) GetMaxInlineBytes() uint64 {
	if x != nil {
		return x.MaxInlineBytes
	}
	return 0
}

func (x *OutputPolicy) GetOverflow() OutputOverflowPolicy {
	if x != nil {
		return x.Overflow
	}
	return OutputOverflowPolicy_OUTPUT_OVERFLOW_POLICY_UNSPECIFIED
}

// CommandInput writes data to the stdin of an already running command.
type CommandInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data contains the exact bytes to write. Empty data is valid.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Close closes stdin after data is written. When data is empty, close=true
	// only closes stdin.
	Close         bool `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInput) Reset() {
	*x = CommandInput{}
	mi := &file_v1_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInput) ProtoMessage() {}

func (x *CommandInput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInput.ProtoReflect.Descriptor instead.
func (*CommandInput) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CommandInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandInput) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

// ResizeTerminal changes the dimensions of an active command PTY.
type ResizeTerminal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Size contains the new terminal dimensions.
	Size          *TerminalSize `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeTerminal) Reset() {
	*x = ResizeTerminal{}
	mi := &file_v1_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeTerminal) ProtoMessage() {}

func (x *ResizeTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeTerminal.ProtoReflect.Descriptor instead.
func (*ResizeTerminal) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ResizeTerminal) GetSize() *TerminalSize {
	if x != nil {
		return x.Size
	}
	return nil
}

// TerminalSize describes a terminal in character cells.
type TerminalSize struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Columns is the terminal width in character cells and must be positive.
	Columns uint32 `protobuf:"varint,1,opt,name=columns,proto3" json:"columns,omitempty"`
	// Rows is the terminal height in character cells and must be positive.
	Rows          uint32 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSize) Reset() {
	*x = TerminalSize{}
	mi := &file_v1_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSize) ProtoMessage() {}

func (x *TerminalSize) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSize.ProtoReflect.Descriptor instead.
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *TerminalSize) GetColumns() uint32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *TerminalSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// SignalCommand asks the agent to signal a running command.
type SignalCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signal is the portable signal selected by the server.
	Signal        Signal `protobuf:"varint,1,opt,name=signal,proto3,enum=graphene.v1.agent.Signal" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalCommand) Reset() {
	*x = SignalCommand{}
	mi := &file_v1_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalCommand) ProtoMessage() {}

func (x *SignalCommand) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalCommand.ProtoReflect.Descriptor instead.
func (*SignalCommand) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SignalCommand) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_SIGNAL_UNSPECIFIED
}

// CommandStarted confirms that the agent successfully started a command.
type CommandStarted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pid is the local operating-system process identifier when one is available.
	Pid           *ProcessId `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandStarted) Reset() {
	*x = CommandStarted{}
	mi := &file_v1_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandStarted) ProtoMessage() {}

func (x *CommandStarted) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandStarted.ProtoReflect.Descriptor instead.
func (*CommandStarted) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CommandStarted) GetPid() *ProcessId {
	if x != nil {
		return x.Pid
	}
	return nil
}

// CommandOutput contains one ordered block of output from a running command.
type CommandOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream identifies the source represented by data.
	Stream OutputStream `protobuf:"varint,1,opt,name=stream,proto3,enum=graphene.v1.agent.OutputStream" json:"stream,omitempty"`
	// Data contains opaque output bytes and is not required to be UTF-8 text.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Sequence starts at one and increases by one across all output frames for
	// the command. It remains monotonic across agent reconnection.
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// DroppedBefore is the number of command-output bytes discarded after the
	// previous delivered frame and before this frame. Graphene exports an
	// explicit OTEL loss marker when this value is non-zero.
	DroppedBefore uint64 `protobuf:"varint,4,opt,name=dropped_before,json=droppedBefore,proto3" json:"dropped_before,omitempty"`
	// ObservedAt is the time at which the agent completed this output frame. It
	// becomes the source timestamp of the corresponding OTEL log record.
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_v1_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CommandOutput) GetStream() OutputStream {
	if x != nil {
		return x.Stream
	}
	return OutputStream_OUTPUT_STREAM_UNSPECIFIED
}

func (x *CommandOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CommandOutput) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CommandOutput) GetDroppedBefore() uint64 {
	if x != nil {
		return x.DroppedBefore
	}
	return 0
}

func (x *CommandOutput) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// OutputStats summarizes one command stream after the command terminates.
type OutputStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream identifies the command stream described by these counters.
	Stream OutputStream `protobuf:"varint,1,opt,name=stream,proto3,enum=graphene.v1.agent.OutputStream" json:"stream,omitempty"`
	// ObservedBytes is the number of bytes the agent drained from the process.
	ObservedBytes uint64 `protobuf:"varint,2,opt,name=observed_bytes,json=observedBytes,proto3" json:"observed_bytes,omitempty"`
	// SentBytes is the number of bytes included in CommandOutput frames.
	SentBytes uint64 `protobuf:"varint,3,opt,name=sent_bytes,json=sentBytes,proto3" json:"sent_bytes,omitempty"`
	// DroppedBytes is the number of observed bytes omitted because of pending
	// buffer overflow or the total max_inline_bytes limit.
	DroppedBytes  uint64 `protobuf:"varint,4,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputStats) Reset() {
	*x = OutputStats{}
	mi := &file_v1_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputStats) ProtoMessage() {}

func (x *OutputStats) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputStats.ProtoReflect.Descriptor instead.
func (*OutputStats) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *OutputStats) GetStream() OutputStream {
	if x != nil {
		return x.Stream
	}
	return OutputStream_OUTPUT_STREAM_UNSPECIFIED
}

func (x *OutputStats) GetObservedBytes() uint64 {
	if x != nil {
		return x.ObservedBytes
	}
	return 0
}

func (x *OutputStats) GetSentBytes() uint64 {
	if x != nil {
		return x.SentBytes
	}
	return 0
}

func (x *OutputStats) GetDroppedBytes() uint64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

// CommandExited is the terminal result of a command that successfully started.
type CommandExited struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ExitCode is the program exit code. A non-zero value is a valid command
	// result and is not an AgentService transport failure.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Signal identifies the signal that ended the command. It is unspecified
	// when the command exited normally.
	Signal Signal `protobuf:"varint,2,opt,name=signal,proto3,enum=graphene.v1.agent.Signal" json:"signal,omitempty"`
	// TimedOut is true when the agent terminated the command because its timeout
	// expired.
	TimedOut bool `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	// Output contains one final counter set for every stream observed during the
	// command. Graphene exports these counters to OTEL and uses them to make any
	// output loss visible.
	Output        []*OutputStats `protobuf:"bytes,4,rep,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExited) Reset() {
	*x = CommandExited{}
	mi := &file_v1_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExited) ProtoMessage() {}

func (x *CommandExited) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExited.ProtoReflect.Descriptor instead.
func (*CommandExited) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CommandExited) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandExited) GetSignal() Signal {
	if x != nil {
		return x.Signal
	}
	return Signal_SIGNAL_UNSPECIFIED
}

func (x *CommandExited) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *CommandExited) GetOutput() []*OutputStats {
	if x != nil {
		return x.Output
	}
	return nil
}

// PutArtifact asks the agent to materialize a server artifact as a local file.
type PutArtifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ArtifactId identifies the immutable server artifact to download.
	ArtifactId *ArtifactId `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Path is the destination path on the agent machine.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Mode contains Unix permission bits. Zero selects the agent's configured
	// default mode on platforms where Unix modes apply.
	Mode uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Overwrite permits atomic replacement of an existing destination. When
	// false, an existing destination produces ERROR_CODE_ALREADY_EXISTS.
	Overwrite bool `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	// Size is the expected complete artifact size in bytes.
	Size uint64 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// Sha256 is the expected raw 32-byte SHA-256 digest of the complete artifact.
	Sha256        []byte `protobuf:"bytes,6,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutArtifact) Reset() {
	*x = PutArtifact{}
	mi := &file_v1_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutArtifact) ProtoMessage() {}

func (x *PutArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutArtifact.ProtoReflect.Descriptor instead.
func (*PutArtifact) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *PutArtifact) GetArtifactId() *ArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

func (x *PutArtifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PutArtifact) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PutArtifact) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *PutArtifact) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutArtifact) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// DownloadArtifactRequest authorizes and identifies one artifact download.
type DownloadArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstructionId identifies the PutArtifact instruction offered to this
	// installation and prevents an agent from enumerating unrelated artifacts.
	InstructionId *InstructionId `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// ArtifactId must match the artifact referenced by that instruction.
	ArtifactId    *ArtifactId `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactRequest) Reset() {
	*x = DownloadArtifactRequest{}
	mi := &file_v1_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactRequest) ProtoMessage() {}

func (x *DownloadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadArtifactRequest) GetInstructionId() *InstructionId {
	if x != nil {
		return x.InstructionId
	}
	return nil
}

func (x *DownloadArtifactRequest) GetArtifactId() *ArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

// DownloadArtifactResponse contains one ordered block of a server-to-agent
// download.
type DownloadArtifactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the zero-based byte position of data in the complete artifact.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Data contains the artifact bytes beginning at offset.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArtifactResponse) Reset() {
	*x = DownloadArtifactResponse{}
	mi := &file_v1_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArtifactResponse) ProtoMessage() {}

func (x *DownloadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArtifactResponse.ProtoReflect.Descriptor instead.
func (*DownloadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *DownloadArtifactResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadArtifactResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ArtifactPlaced confirms that a downloaded artifact was committed locally.
type ArtifactPlaced struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path is the final destination path on the agent machine.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Size is the number of bytes written to the final file.
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Sha256 is the raw 32-byte digest computed over the bytes actually written.
	Sha256        []byte `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactPlaced) Reset() {
	*x = ArtifactPlaced{}
	mi := &file_v1_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactPlaced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactPlaced) ProtoMessage() {}

func (x *ArtifactPlaced) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactPlaced.ProtoReflect.Descriptor instead.
func (*ArtifactPlaced) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ArtifactPlaced) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArtifactPlaced) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactPlaced) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// CollectArtifact asks the agent to upload a machine-local file as an artifact.
type CollectArtifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ArtifactId is reserved and persisted by the server before this instruction
	// is delivered. Every retry of this instruction reuses the same value.
	ArtifactId *ArtifactId `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Path is the source file path on the agent machine.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Name is the user-facing artifact name within the owning operation or run.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectArtifact) Reset() {
	*x = CollectArtifact{}
	mi := &file_v1_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectArtifact) ProtoMessage() {}

func (x *CollectArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectArtifact.ProtoReflect.Descriptor instead.
func (*CollectArtifact) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *CollectArtifact) GetArtifactId() *ArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

func (x *CollectArtifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CollectArtifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UploadArtifactRequest is one frame in an agent-to-server artifact upload.
type UploadArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frame contains exactly one upload state-machine frame.
	//
	// Types that are valid to be assigned to Frame:
	//
	//	*UploadArtifactRequest_Begin
	//	*UploadArtifactRequest_Chunk
	//	*UploadArtifactRequest_Finish
	Frame         isUploadArtifactRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactRequest) Reset() {
	*x = UploadArtifactRequest{}
	mi := &file_v1_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactRequest) ProtoMessage() {}

func (x *UploadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactRequest.ProtoReflect.Descriptor instead.
func (*UploadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *UploadArtifactRequest) GetFrame() isUploadArtifactRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *UploadArtifactRequest) GetBegin() *BeginArtifactUpload {
	if x != nil {
		if x, ok := x.Frame.(*UploadArtifactRequest_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *UploadArtifactRequest) GetChunk() *ArtifactUploadChunk {
	if x != nil {
		if x, ok := x.Frame.(*UploadArtifactRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *UploadArtifactRequest) GetFinish() *FinishArtifactUpload {
	if x != nil {
		if x, ok := x.Frame.(*UploadArtifactRequest_Finish); ok {
			return x.Finish
		}
	}
	return nil
}

type isUploadArtifactRequest_Frame interface {
	isUploadArtifactRequest_Frame()
}

type UploadArtifactRequest_Begin struct {
	// Begin starts the upload and must be the first frame.
	Begin *BeginArtifactUpload `protobuf:"bytes,1,opt,name=begin,proto3,oneof"`
}

type UploadArtifactRequest_Chunk struct {
	// Chunk contributes one ordered block after begin and before finish.
	Chunk *ArtifactUploadChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type UploadArtifactRequest_Finish struct {
	// Finish completes the upload and must be the final frame.
	Finish *FinishArtifactUpload `protobuf:"bytes,3,opt,name=finish,proto3,oneof"`
}

func (*UploadArtifactRequest_Begin) isUploadArtifactRequest_Frame() {}

func (*UploadArtifactRequest_Chunk) isUploadArtifactRequest_Frame() {}

func (*UploadArtifactRequest_Finish) isUploadArtifactRequest_Frame() {}

// BeginArtifactUpload opens one upload attempt for a CollectArtifact instruction.
type BeginArtifactUpload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// InstructionId identifies and authorizes the CollectArtifact instruction.
	InstructionId *InstructionId `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// ArtifactId must match the artifact reserved for the instruction.
	ArtifactId *ArtifactId `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Size is the source file size observed before streaming begins.
	Size          uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginArtifactUpload) Reset() {
	*x = BeginArtifactUpload{}
	mi := &file_v1_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginArtifactUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginArtifactUpload) ProtoMessage() {}

func (x *BeginArtifactUpload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginArtifactUpload.ProtoReflect.Descriptor instead.
func (*BeginArtifactUpload) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *BeginArtifactUpload) GetInstructionId() *InstructionId {
	if x != nil {
		return x.InstructionId
	}
	return nil
}

func (x *BeginArtifactUpload) GetArtifactId() *ArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

func (x *BeginArtifactUpload) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ArtifactUploadChunk contains one ordered block of an agent-to-server upload.
type ArtifactUploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the zero-based byte position of data in the complete artifact.
	// The first chunk starts at zero and every later chunk starts immediately
	// after the previous one.
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Data contains artifact bytes beginning at offset.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactUploadChunk) Reset() {
	*x = ArtifactUploadChunk{}
	mi := &file_v1_agent_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUploadChunk) ProtoMessage() {}

func (x *ArtifactUploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUploadChunk.ProtoReflect.Descriptor instead.
func (*ArtifactUploadChunk) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ArtifactUploadChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ArtifactUploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// FinishArtifactUpload closes an upload after all chunks have been sent.
type FinishArtifactUpload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Size is the total number of bytes sent by the agent.
	Size uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Sha256 is the raw 32-byte digest computed by the agent while streaming.
	// The server verifies it against its own independently computed digest.
	Sha256        []byte `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishArtifactUpload) Reset() {
	*x = FinishArtifactUpload{}
	mi := &file_v1_agent_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishArtifactUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishArtifactUpload) ProtoMessage() {}

func (x *FinishArtifactUpload) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishArtifactUpload.ProtoReflect.Descriptor instead.
func (*FinishArtifactUpload) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{26}
}

func (x *FinishArtifactUpload) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FinishArtifactUpload) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// UploadArtifactResponse describes the immutable artifact committed by the
// server.
type UploadArtifactResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ArtifactId is the stable identifier reserved by CollectArtifact.
	ArtifactId *ArtifactId `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Size is the canonical byte size verified by the server.
	Size uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Sha256 is the canonical raw 32-byte digest computed by the server.
	Sha256        []byte `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactResponse) Reset() {
	*x = UploadArtifactResponse{}
	mi := &file_v1_agent_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactResponse) ProtoMessage() {}

func (x *UploadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactResponse.ProtoReflect.Descriptor instead.
func (*UploadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{27}
}

func (x *UploadArtifactResponse) GetArtifactId() *ArtifactId {
	if x != nil {
		return x.ArtifactId
	}
	return nil
}

func (x *UploadArtifactResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadArtifactResponse) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// CancelOperation requests cancellation of the operation correlated by the
// containing ConnectResponse.id. It has no additional parameters.
type CancelOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperation) Reset() {
	*x = CancelOperation{}
	mi := &file_v1_agent_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperation) ProtoMessage() {}

func (x *CancelOperation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperation.ProtoReflect.Descriptor instead.
func (*CancelOperation) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{28}
}

// OperationFailed reports that an instruction could not be completed normally.
type OperationFailed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code classifies the failure for programmatic handling.
	Code ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=graphene.v1.agent.ErrorCode" json:"code,omitempty"`
	// Message is a human-readable explanation suitable for diagnostics. It must
	// not contain secret values.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationFailed) Reset() {
	*x = OperationFailed{}
	mi := &file_v1_agent_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationFailed) ProtoMessage() {}

func (x *OperationFailed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationFailed.ProtoReflect.Descriptor instead.
func (*OperationFailed) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{29}
}

func (x *OperationFailed) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *OperationFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Ping requests an immediate Pong on Connect and carries no fields.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_v1_agent_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{30}
}

// Pong answers Ping on Connect and carries no fields.
type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_v1_agent_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_v1_agent_agent_proto_rawDescGZIP(), []int{31}
}

var File_v1_agent_agent_proto protoreflect.FileDescriptor

const file_v1_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x14v1/agent/agent.proto\x12\x11graphene.v1.agent\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\x0eInstallationId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"%\n" +
	"\rInstructionId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\"\n" +
	"\n" +
	"ArtifactId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tProcessId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\"\x84\x05\n" +
	"\x0eConnectRequest\x12G\n" +
	"\x0einstruction_id\x18\x01 \x01(\v2 .graphene.v1.agent.InstructionIdR\rinstructionId\x120\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x18.graphene.v1.agent.HelloH\x00R\x05hello\x12<\n" +
	"\theartbeat\x18\v \x01(\v2\x1c.graphene.v1.agent.HeartbeatH\x00R\theartbeat\x12L\n" +
	"\x0fcommand_started\x18\f \x01(\v2!.graphene.v1.agent.CommandStartedH\x00R\x0ecommandStarted\x12I\n" +
	"\x0ecommand_output\x18\r \x01(\v2 .graphene.v1.agent.CommandOutputH\x00R\rcommandOutput\x12I\n" +
	"\x0ecommand_exited\x18\x0e \x01(\v2 .graphene.v1.agent.CommandExitedH\x00R\rcommandExited\x12L\n" +
	"\x0fartifact_placed\x18\x0f \x01(\v2!.graphene.v1.agent.ArtifactPlacedH\x00R\x0eartifactPlaced\x12O\n" +
	"\x10operation_failed\x18\x10 \x01(\v2\".graphene.v1.agent.OperationFailedH\x00R\x0foperationFailed\x12-\n" +
	"\x04pong\x18\x11 \x01(\v2\x17.graphene.v1.agent.PongH\x00R\x04pongB\a\n" +
	"\x05event\"\x8b\x05\n" +
	"\x0fConnectResponse\x120\n" +
	"\x02id\x18\x01 \x01(\v2 .graphene.v1.agent.InstructionIdR\x02id\x12@\n" +
	"\vrun_command\x18\n" +
	" \x01(\v2\x1d.graphene.v1.agent.RunCommandH\x00R\n" +
	"runCommand\x12F\n" +
	"\rcommand_input\x18\v \x01(\v2\x1f.graphene.v1.agent.CommandInputH\x00R\fcommandInput\x12L\n" +
	"\x0fresize_terminal\x18\f \x01(\v2!.graphene.v1.agent.ResizeTerminalH\x00R\x0eresizeTerminal\x12I\n" +
	"\x0esignal_command\x18\r \x01(\v2 .graphene.v1.agent.SignalCommandH\x00R\rsignalCommand\x12C\n" +
	"\fput_artifact\x18\x0e \x01(\v2\x1e.graphene.v1.agent.PutArtifactH\x00R\vputArtifact\x12O\n" +
	"\x10cancel_operation\x18\x0f \x01(\v2\".graphene.v1.agent.CancelOperationH\x00R\x0fcancelOperation\x12-\n" +
	"\x04ping\x18\x10 \x01(\v2\x17.graphene.v1.agent.PingH\x00R\x04ping\x12O\n" +
	"\x10collect_artifact\x18\x11 \x01(\v2\".graphene.v1.agent.CollectArtifactH\x00R\x0fcollectArtifactB\r\n" +
	"\vinstruction\"\xac\x02\n" +
	"\x05Hello\x12J\n" +
	"\x0finstallation_id\x18\x01 \x01(\v2!.graphene.v1.agent.InstallationIdR\x0einstallationId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12)\n" +
	"\x10operating_system\x18\x04 \x01(\tR\x0foperatingSystem\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12A\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x1d.graphene.v1.agent.CapabilityR\fcapabilities\"c\n" +
	"\tHeartbeat\x12V\n" +
	"\x16active_instruction_ids\x18\x01 \x03(\v2 .graphene.v1.agent.InstructionIdR\x14activeInstructionIds\"\xb5\x03\n" +
	"\n" +
	"RunCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12P\n" +
	"\venvironment\x18\x03 \x03(\v2..graphene.v1.agent.RunCommand.EnvironmentEntryR\venvironment\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1a\n" +
	"\bterminal\x18\x05 \x01(\bR\bterminal\x12D\n" +
	"\rterminal_size\x18\x06 \x01(\v2\x1f.graphene.v1.agent.TerminalSizeR\fterminalSize\x127\n" +
	"\x06output\x18\a \x01(\v2\x1f.graphene.v1.agent.OutputPolicyR\x06output\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x02\n" +
	"\fOutputPolicy\x12&\n" +
	"\x0fmax_frame_bytes\x18\x01 \x01(\rR\rmaxFrameBytes\x12@\n" +
	"\x0eflush_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rflushInterval\x12*\n" +
	"\x11max_pending_bytes\x18\x03 \x01(\x04R\x0fmaxPendingBytes\x12(\n" +
	"\x10max_inline_bytes\x18\x04 \x01(\x04R\x0emaxInlineBytes\x12C\n" +
	"\boverflow\x18\x05 \x01(\x0e2'.graphene.v1.agent.OutputOverflowPolicyR\boverflow\"8\n" +
	"\fCommandInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05close\x18\x02 \x01(\bR\x05close\"E\n" +
	"\x0eResizeTerminal\x123\n" +
	"\x04size\x18\x01 \x01(\v2\x1f.graphene.v1.agent.TerminalSizeR\x04size\"<\n" +
	"\fTerminalSize\x12\x18\n" +
	"\acolumns\x18\x01 \x01(\rR\acolumns\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"B\n" +
	"\rSignalCommand\x121\n" +
	"\x06signal\x18\x01 \x01(\x0e2\x19.graphene.v1.agent.SignalR\x06signal\"@\n" +
	"\x0eCommandStarted\x12.\n" +
	"\x03pid\x18\x01 \x01(\v2\x1c.graphene.v1.agent.ProcessIdR\x03pid\"\xdc\x01\n" +
	"\rCommandOutput\x127\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1f.graphene.v1.agent.OutputStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12%\n" +
	"\x0edropped_before\x18\x04 \x01(\x04R\rdroppedBefore\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\xb1\x01\n" +
	"\vOutputStats\x127\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1f.graphene.v1.agent.OutputStreamR\x06stream\x12%\n" +
	"\x0eobserved_bytes\x18\x02 \x01(\x04R\robservedBytes\x12\x1d\n" +
	"\n" +
	"sent_bytes\x18\x03 \x01(\x04R\tsentBytes\x12#\n" +
	"\rdropped_bytes\x18\x04 \x01(\x04R\fdroppedBytes\"\xb4\x01\n" +
	"\rCommandExited\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x121\n" +
	"\x06signal\x18\x02 \x01(\x0e2\x19.graphene.v1.agent.SignalR\x06signal\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\x126\n" +
	"\x06output\x18\x04 \x03(\v2\x1e.graphene.v1.agent.OutputStatsR\x06output\"\xbf\x01\n" +
	"\vPutArtifact\x12>\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1d.graphene.v1.agent.ArtifactIdR\n" +
	"artifactId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x1c\n" +
	"\toverwrite\x18\x04 \x01(\bR\toverwrite\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x06 \x01(\fR\x06sha256\"\xa2\x01\n" +
	"\x17DownloadArtifactRequest\x12G\n" +
	"\x0einstruction_id\x18\x01 \x01(\v2 .graphene.v1.agent.InstructionIdR\rinstructionId\x12>\n" +
	"\vartifact_id\x18\x02 \x01(\v2\x1d.graphene.v1.agent.ArtifactIdR\n" +
	"artifactId\"F\n" +
	"\x18DownloadArtifactResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"P\n" +
	"\x0eArtifactPlaced\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\"y\n" +
	"\x0fCollectArtifact\x12>\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1d.graphene.v1.agent.ArtifactIdR\n" +
	"artifactId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xe3\x01\n" +
	"\x15UploadArtifactRequest\x12>\n" +
	"\x05begin\x18\x01 \x01(\v2&.graphene.v1.agent.BeginArtifactUploadH\x00R\x05begin\x12>\n" +
	"\x05chunk\x18\x02 \x01(\v2&.graphene.v1.agent.ArtifactUploadChunkH\x00R\x05chunk\x12A\n" +
	"\x06finish\x18\x03 \x01(\v2'.graphene.v1.agent.FinishArtifactUploadH\x00R\x06finishB\a\n" +
	"\x05frame\"\xb2\x01\n" +
	"\x13BeginArtifactUpload\x12G\n" +
	"\x0einstruction_id\x18\x01 \x01(\v2 .graphene.v1.agent.InstructionIdR\rinstructionId\x12>\n" +
	"\vartifact_id\x18\x02 \x01(\v2\x1d.graphene.v1.agent.ArtifactIdR\n" +
	"artifactId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"A\n" +
	"\x13ArtifactUploadChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\x14FinishArtifactUpload\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"\x84\x01\n" +
	"\x16UploadArtifactResponse\x12>\n" +
	"\vartifact_id\x18\x01 \x01(\v2\x1d.graphene.v1.agent.ArtifactIdR\n" +
	"artifactId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\"\x11\n" +
	"\x0fCancelOperation\"]\n" +
	"\x0fOperationFailed\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.graphene.v1.agent.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong*\x97\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CAPABILITY_COMMAND\x10\x01\x12\x17\n" +
	"\x13CAPABILITY_TERMINAL\x10\x02\x12\x1b\n" +
	"\x17CAPABILITY_PUT_ARTIFACT\x10\x03\x12\x1f\n" +
	"\x1bCAPABILITY_COLLECT_ARTIFACT\x10\x04*\x8e\x01\n" +
	"\x14OutputOverflowPolicy\x12&\n" +
	"\"OUTPUT_OVERFLOW_POLICY_UNSPECIFIED\x10\x00\x12&\n" +
	"\"OUTPUT_OVERFLOW_POLICY_DROP_OLDEST\x10\x01\x12&\n" +
	"\"OUTPUT_OVERFLOW_POLICY_DROP_NEWEST\x10\x02*]\n" +
	"\x06Signal\x12\x16\n" +
	"\x12SIGNAL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SIGNAL_INTERRUPT\x10\x01\x12\x14\n" +
	"\x10SIGNAL_TERMINATE\x10\x02\x12\x0f\n" +
	"\vSIGNAL_KILL\x10\x03*}\n" +
	"\fOutputStream\x12\x1d\n" +
	"\x19OUTPUT_STREAM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OUTPUT_STREAM_STDOUT\x10\x01\x12\x18\n" +
	"\x14OUTPUT_STREAM_STDERR\x10\x02\x12\x1a\n" +
	"\x16OUTPUT_STREAM_TERMINAL\x10\x03*\xa7\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x03\x12 \n" +
	"\x1cERROR_CODE_PERMISSION_DENIED\x10\x04\x12\x11\n" +
	"\rERROR_CODE_IO\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_START_FAILED\x10\x06\x12 \n" +
	"\x1cERROR_CODE_CHECKSUM_MISMATCH\x10\a\x12\x17\n" +
	"\x13ERROR_CODE_CANCELED\x10\b\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\t2\xbc\x02\n" +
	"\fAgentService\x12T\n" +
	"\aConnect\x12!.graphene.v1.agent.ConnectRequest\x1a\".graphene.v1.agent.ConnectResponse(\x010\x01\x12m\n" +
	"\x10DownloadArtifact\x12*.graphene.v1.agent.DownloadArtifactRequest\x1a+.graphene.v1.agent.DownloadArtifactResponse0\x01\x12g\n" +
	"\x0eUploadArtifact\x12(.graphene.v1.agent.UploadArtifactRequest\x1a).graphene.v1.agent.UploadArtifactResponse(\x01B=Z;github.com/graphene-ci/graphene/graphenepb/v1/agent;agentpbb\x06proto3"

var (
	file_v1_agent_agent_proto_rawDescOnce sync.Once
	file_v1_agent_agent_proto_rawDescData []byte
)

func file_v1_agent_agent_proto_rawDescGZIP() []byte {
	file_v1_agent_agent_proto_rawDescOnce.Do(func() {
		file_v1_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_agent_proto_rawDesc), len(file_v1_agent_agent_proto_rawDesc)))
	})
	return file_v1_agent_agent_proto_rawDescData
}

var file_v1_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_v1_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_v1_agent_agent_proto_goTypes = []any{
	(Capability)(0),                  // 0: graphene.v1.agent.Capability
	(OutputOverflowPolicy)(0),        // 1: graphene.v1.agent.OutputOverflowPolicy
	(Signal)(0),                      // 2: graphene.v1.agent.Signal
	(OutputStream)(0),                // 3: graphene.v1.agent.OutputStream
	(ErrorCode)(0),                   // 4: graphene.v1.agent.ErrorCode
	(*InstallationId)(nil),           // 5: graphene.v1.agent.InstallationId
	(*InstructionId)(nil),            // 6: graphene.v1.agent.InstructionId
	(*ArtifactId)(nil),               // 7: graphene.v1.agent.ArtifactId
	(*ProcessId)(nil),                // 8: graphene.v1.agent.ProcessId
	(*ConnectRequest)(nil),           // 9: graphene.v1.agent.ConnectRequest
	(*ConnectResponse)(nil),          // 10: graphene.v1.agent.ConnectResponse
	(*Hello)(nil),                    // 11: graphene.v1.agent.Hello
	(*Heartbeat)(nil),                // 12: graphene.v1.agent.Heartbeat
	(*RunCommand)(nil),               // 13: graphene.v1.agent.RunCommand
	(*OutputPolicy)(nil),             // 14: graphene.v1.agent.OutputPolicy
	(*CommandInput)(nil),             // 15: graphene.v1.agent.CommandInput
	(*ResizeTerminal)(nil),           // 16: graphene.v1.agent.ResizeTerminal
	(*TerminalSize)(nil),             // 17: graphene.v1.agent.TerminalSize
	(*SignalCommand)(nil),            // 18: graphene.v1.agent.SignalCommand
	(*CommandStarted)(nil),           // 19: graphene.v1.agent.CommandStarted
	(*CommandOutput)(nil),            // 20: graphene.v1.agent.CommandOutput
	(*OutputStats)(nil),              // 21: graphene.v1.agent.OutputStats
	(*CommandExited)(nil),            // 22: graphene.v1.agent.CommandExited
	(*PutArtifact)(nil),              // 23: graphene.v1.agent.PutArtifact
	(*DownloadArtifactRequest)(nil),  // 24: graphene.v1.agent.DownloadArtifactRequest
	(*DownloadArtifactResponse)(nil), // 25: graphene.v1.agent.DownloadArtifactResponse
	(*ArtifactPlaced)(nil),           // 26: graphene.v1.agent.ArtifactPlaced
	(*CollectArtifact)(nil),          // 27: graphene.v1.agent.CollectArtifact
	(*UploadArtifactRequest)(nil),    // 28: graphene.v1.agent.UploadArtifactRequest
	(*BeginArtifactUpload)(nil),      // 29: graphene.v1.agent.BeginArtifactUpload
	(*ArtifactUploadChunk)(nil),      // 30: graphene.v1.agent.ArtifactUploadChunk
	(*FinishArtifactUpload)(nil),     // 31: graphene.v1.agent.FinishArtifactUpload
	(*UploadArtifactResponse)(nil),   // 32: graphene.v1.agent.UploadArtifactResponse
	(*CancelOperation)(nil),          // 33: graphene.v1.agent.CancelOperation
	(*OperationFailed)(nil),          // 34: graphene.v1.agent.OperationFailed
	(*Ping)(nil),                     // 35: graphene.v1.agent.Ping
	(*Pong)(nil),                     // 36: graphene.v1.agent.Pong
	nil,                              // 37: graphene.v1.agent.RunCommand.EnvironmentEntry
	(*durationpb.Duration)(nil),      // 38: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),    // 39: google.protobuf.Timestamp
}
var file_v1_agent_agent_proto_depIdxs = []int32{
	6,  // 0: graphene.v1.agent.ConnectRequest.instruction_id:type_name -> graphene.v1.agent.InstructionId
	11, // 1: graphene.v1.agent.ConnectRequest.hello:type_name -> graphene.v1.agent.Hello
	12, // 2: graphene.v1.agent.ConnectRequest.heartbeat:type_name -> graphene.v1.agent.Heartbeat
	19, // 3: graphene.v1.agent.ConnectRequest.command_started:type_name -> graphene.v1.agent.CommandStarted
	20, // 4: graphene.v1.agent.ConnectRequest.command_output:type_name -> graphene.v1.agent.CommandOutput
	22, // 5: graphene.v1.agent.ConnectRequest.command_exited:type_name -> graphene.v1.agent.CommandExited
	26, // 6: graphene.v1.agent.ConnectRequest.artifact_placed:type_name -> graphene.v1.agent.ArtifactPlaced
	34, // 7: graphene.v1.agent.ConnectRequest.operation_failed:type_name -> graphene.v1.agent.OperationFailed
	36, // 8: graphene.v1.agent.ConnectRequest.pong:type_name -> graphene.v1.agent.Pong
	6,  // 9: graphene.v1.agent.ConnectResponse.id:type_name -> graphene.v1.agent.InstructionId
	13, // 10: graphene.v1.agent.ConnectResponse.run_command:type_name -> graphene.v1.agent.RunCommand
	15, // 11: graphene.v1.agent.ConnectResponse.command_input:type_name -> graphene.v1.agent.CommandInput
	16, // 12: graphene.v1.agent.ConnectResponse.resize_terminal:type_name -> graphene.v1.agent.ResizeTerminal
	18, // 13: graphene.v1.agent.ConnectResponse.signal_command:type_name -> graphene.v1.agent.SignalCommand
	23, // 14: graphene.v1.agent.ConnectResponse.put_artifact:type_name -> graphene.v1.agent.PutArtifact
	33, // 15: graphene.v1.agent.ConnectResponse.cancel_operation:type_name -> graphene.v1.agent.CancelOperation
	35, // 16: graphene.v1.agent.ConnectResponse.ping:type_name -> graphene.v1.agent.Ping
	27, // 17: graphene.v1.agent.ConnectResponse.collect_artifact:type_name -> graphene.v1.agent.CollectArtifact
	5,  // 18: graphene.v1.agent.Hello.installation_id:type_name -> graphene.v1.agent.InstallationId
	0,  // 19: graphene.v1.agent.Hello.capabilities:type_name -> graphene.v1.agent.Capability
	6,  // 20: graphene.v1.agent.Heartbeat.active_instruction_ids:type_name -> graphene.v1.agent.InstructionId
	37, // 21: graphene.v1.agent.RunCommand.environment:type_name -> graphene.v1.agent.RunCommand.EnvironmentEntry
	38, // 22: graphene.v1.agent.RunCommand.timeout:type_name -> google.protobuf.Duration
	17, // 23: graphene.v1.agent.RunCommand.terminal_size:type_name -> graphene.v1.agent.TerminalSize
	14, // 24: graphene.v1.agent.RunCommand.output:type_name -> graphene.v1.agent.OutputPolicy
	38, // 25: graphene.v1.agent.OutputPolicy.flush_interval:type_name -> google.protobuf.Duration
	1,  // 26: graphene.v1.agent.OutputPolicy.overflow:type_name -> graphene.v1.agent.OutputOverflowPolicy
	17, // 27: graphene.v1.agent.ResizeTerminal.size:type_name -> graphene.v1.agent.TerminalSize
	2,  // 28: graphene.v1.agent.SignalCommand.signal:type_name -> graphene.v1.agent.Signal
	8,  // 29: graphene.v1.agent.CommandStarted.pid:type_name -> graphene.v1.agent.ProcessId
	3,  // 30: graphene.v1.agent.CommandOutput.stream:type_name -> graphene.v1.agent.OutputStream
	39, // 31: graphene.v1.agent.CommandOutput.observed_at:type_name -> google.protobuf.Timestamp
	3,  // 32: graphene.v1.agent.OutputStats.stream:type_name -> graphene.v1.agent.OutputStream
	2,  // 33: graphene.v1.agent.CommandExited.signal:type_name -> graphene.v1.agent.Signal
	21, // 34: graphene.v1.agent.CommandExited.output:type_name -> graphene.v1.agent.OutputStats
	7,  // 35: graphene.v1.agent.PutArtifact.artifact_id:type_name -> graphene.v1.agent.ArtifactId
	6,  // 36: graphene.v1.agent.DownloadArtifactRequest.instruction_id:type_name -> graphene.v1.agent.InstructionId
	7,  // 37: graphene.v1.agent.DownloadArtifactRequest.artifact_id:type_name -> graphene.v1.agent.ArtifactId
	7,  // 38: graphene.v1.agent.CollectArtifact.artifact_id:type_name -> graphene.v1.agent.ArtifactId
	29, // 39: graphene.v1.agent.UploadArtifactRequest.begin:type_name -> graphene.v1.agent.BeginArtifactUpload
	30, // 40: graphene.v1.agent.UploadArtifactRequest.chunk:type_name -> graphene.v1.agent.ArtifactUploadChunk
	31, // 41: graphene.v1.agent.UploadArtifactRequest.finish:type_name -> graphene.v1.agent.FinishArtifactUpload
	6,  // 42: graphene.v1.agent.BeginArtifactUpload.instruction_id:type_name -> graphene.v1.agent.InstructionId
	7,  // 43: graphene.v1.agent.BeginArtifactUpload.artifact_id:type_name -> graphene.v1.agent.ArtifactId
	7,  // 44: graphene.v1.agent.UploadArtifactResponse.artifact_id:type_name -> graphene.v1.agent.ArtifactId
	4,  // 45: graphene.v1.agent.OperationFailed.code:type_name -> graphene.v1.agent.ErrorCode
	9,  // 46: graphene.v1.agent.AgentService.Connect:input_type -> graphene.v1.agent.ConnectRequest
	24, // 47: graphene.v1.agent.AgentService.DownloadArtifact:input_type -> graphene.v1.agent.DownloadArtifactRequest
	28, // 48: graphene.v1.agent.AgentService.UploadArtifact:input_type -> graphene.v1.agent.UploadArtifactRequest
	10, // 49: graphene.v1.agent.AgentService.Connect:output_type -> graphene.v1.agent.ConnectResponse
	25, // 50: graphene.v1.agent.AgentService.DownloadArtifact:output_type -> graphene.v1.agent.DownloadArtifactResponse
	32, // 51: graphene.v1.agent.AgentService.UploadArtifact:output_type -> graphene.v1.agent.UploadArtifactResponse
	49, // [49:52] is the sub-list for method output_type
	46, // [46:49] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_v1_agent_agent_proto_init() }
func file_v1_agent_agent_proto_init() {
	if File_v1_agent_agent_proto != nil {
		return
	}
	file_v1_agent_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ConnectRequest_Hello)(nil),
		(*ConnectRequest_Heartbeat)(nil),
		(*ConnectRequest_CommandStarted)(nil),
		(*ConnectRequest_CommandOutput)(nil),
		(*ConnectRequest_CommandExited)(nil),
		(*ConnectRequest_ArtifactPlaced)(nil),
		(*ConnectRequest_OperationFailed)(nil),
		(*ConnectRequest_Pong)(nil),
	}
	file_v1_agent_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*ConnectResponse_RunCommand)(nil),
		(*ConnectResponse_CommandInput)(nil),
		(*ConnectResponse_ResizeTerminal)(nil),
		(*ConnectResponse_SignalCommand)(nil),
		(*ConnectResponse_PutArtifact)(nil),
		(*ConnectResponse_CancelOperation)(nil),
		(*ConnectResponse_Ping)(nil),
		(*ConnectResponse_CollectArtifact)(nil),
	}
	file_v1_agent_agent_proto_msgTypes[23].OneofWrappers = []any{
		(*UploadArtifactRequest_Begin)(nil),
		(*UploadArtifactRequest_Chunk)(nil),
		(*UploadArtifactRequest_Finish)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_agent_proto_rawDesc), len(file_v1_agent_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_agent_agent_proto_goTypes,
		DependencyIndexes: file_v1_agent_agent_proto_depIdxs,
		EnumInfos:         file_v1_agent_agent_proto_enumTypes,
		MessageInfos:      file_v1_agent_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_agent_proto = out.File
	file_v1_agent_agent_proto_goTypes = nil
	file_v1_agent_agent_proto_depIdxs = nil
}
