// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/blob/blob.proto

// Its own proto package, so its messages may be named for what they do.
// Blobs are a service beside the kernel rather than part of it, and a
// flat namespace was making every name here apologise for one over there:
// a Delete that had to be called DeleteBlob because the kernel deletes
// things too.

package blobpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlobService_Stat_FullMethodName     = "/graphene.blob.v1.BlobService/Stat"
	BlobService_Upload_FullMethodName   = "/graphene.blob.v1.BlobService/Upload"
	BlobService_Download_FullMethodName = "/graphene.blob.v1.BlobService/Download"
	BlobService_Delete_FullMethodName   = "/graphene.blob.v1.BlobService/Delete"
)

// BlobServiceClient is the client API for BlobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bytes, on a wire.
//
// A separate service from the kernel because it is a separate kind of
// thing. A resource is a small value that travels the revision log and
// every watch stream; a blob is somebody's binary, and putting one in the
// log would mean every watcher downloading it to learn that it changed.
// The kernel keeps what a blob IS — a reference in some resource's spec —
// and this keeps the bytes.
//
// The id is opaque and the server issues it. A checksum is NOT an
// address: two blobs with the same bytes are two blobs, deleting one does
// not delete the other, and a caller that computed a hash has not thereby
// learned where anything is. What the checksum is for is integrity — the
// reader verifies what it got against what it was told.
type BlobServiceClient interface {
	// Stat reports what is under an id, without moving the bytes.
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// Upload streams bytes in and returns the id they were given.
	//
	// Data frames, then one finish frame. The declaration comes LAST
	// because that is when a sender streaming a file knows it: a checksum
	// is what the bytes turned out to be, and demanding it up front would
	// mean reading everything twice or not declaring at all.
	//
	// A stream that ends without a finish frame is an upload nobody
	// completed, and nothing is stored. That is what makes abandoning one
	// a thing the wire can say rather than a thing the server has to guess
	// from a closed connection.
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error)
	// Download streams bytes out: one info frame, then data.
	//
	// The info comes first so a reader knows the size before the bytes and
	// can verify the checksum after them, without a second call.
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error)
	// Delete removes a blob. Whoever calls it is asserting that nothing
	// refers to it any more; the kernel does not know, because a reference
	// lives in a resource's spec and this service does not read those.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type blobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobServiceClient(cc grpc.ClientConnInterface) BlobServiceClient {
	return &blobServiceClient{cc}
}

func (c *blobServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, BlobService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadRequest, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobService_ServiceDesc.Streams[0], BlobService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadRequest, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_UploadClient = grpc.ClientStreamingClient[UploadRequest, UploadResponse]

func (c *blobServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlobService_ServiceDesc.Streams[1], BlobService_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_DownloadClient = grpc.ServerStreamingClient[DownloadResponse]

func (c *blobServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, BlobService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobServiceServer is the server API for BlobService service.
// All implementations must embed UnimplementedBlobServiceServer
// for forward compatibility.
//
// Bytes, on a wire.
//
// A separate service from the kernel because it is a separate kind of
// thing. A resource is a small value that travels the revision log and
// every watch stream; a blob is somebody's binary, and putting one in the
// log would mean every watcher downloading it to learn that it changed.
// The kernel keeps what a blob IS — a reference in some resource's spec —
// and this keeps the bytes.
//
// The id is opaque and the server issues it. A checksum is NOT an
// address: two blobs with the same bytes are two blobs, deleting one does
// not delete the other, and a caller that computed a hash has not thereby
// learned where anything is. What the checksum is for is integrity — the
// reader verifies what it got against what it was told.
type BlobServiceServer interface {
	// Stat reports what is under an id, without moving the bytes.
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// Upload streams bytes in and returns the id they were given.
	//
	// Data frames, then one finish frame. The declaration comes LAST
	// because that is when a sender streaming a file knows it: a checksum
	// is what the bytes turned out to be, and demanding it up front would
	// mean reading everything twice or not declaring at all.
	//
	// A stream that ends without a finish frame is an upload nobody
	// completed, and nothing is stored. That is what makes abandoning one
	// a thing the wire can say rather than a thing the server has to guess
	// from a closed connection.
	Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error
	// Download streams bytes out: one info frame, then data.
	//
	// The info comes first so a reader knows the size before the bytes and
	// can verify the checksum after them, without a second call.
	Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error
	// Delete removes a blob. Whoever calls it is asserting that nothing
	// refers to it any more; the kernel does not know, because a reference
	// lives in a resource's spec and this service does not read those.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedBlobServiceServer()
}

// UnimplementedBlobServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobServiceServer struct{}

func (UnimplementedBlobServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedBlobServiceServer) Upload(grpc.ClientStreamingServer[UploadRequest, UploadResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedBlobServiceServer) Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadResponse]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedBlobServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBlobServiceServer) mustEmbedUnimplementedBlobServiceServer() {}
func (UnimplementedBlobServiceServer) testEmbeddedByValue()                     {}

// UnsafeBlobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobServiceServer will
// result in compilation errors.
type UnsafeBlobServiceServer interface {
	mustEmbedUnimplementedBlobServiceServer()
}

func RegisterBlobServiceServer(s grpc.ServiceRegistrar, srv BlobServiceServer) {
	// If the following call panics, it indicates UnimplementedBlobServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobService_ServiceDesc, srv)
}

func _BlobService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobServiceServer).Upload(&grpc.GenericServerStream[UploadRequest, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_UploadServer = grpc.ClientStreamingServer[UploadRequest, UploadResponse]

func _BlobService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobServiceServer).Download(m, &grpc.GenericServerStream[DownloadRequest, DownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlobService_DownloadServer = grpc.ServerStreamingServer[DownloadResponse]

func _BlobService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlobService_ServiceDesc is the grpc.ServiceDesc for BlobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.blob.v1.BlobService",
	HandlerType: (*BlobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _BlobService_Stat_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BlobService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _BlobService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _BlobService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "v1/blob/blob.proto",
}
