// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: v1/blob/blob.proto

// Its own proto package, so its messages may be named for what they do.
// Blobs are a service beside the kernel rather than part of it, and a
// flat namespace was making every name here apologise for one over there:
// a Delete that had to be called DeleteBlob because the kernel deletes
// things too.

package blobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_ALGORITHM_SHA256      Algorithm = 1
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_SHA256",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_SHA256":      1,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_blob_blob_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_v1_blob_blob_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{0}
}

// Ref is where bytes are: an opaque handle the server issued.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_v1_blob_blob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{0}
}

func (x *Ref) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Checksum is what the bytes should hash to.
//
// The algorithm travels with the value because a bare 32 bytes is only
// meaningful to a reader who already agreed which function produced them,
// and "everyone knows it is sha256" is an agreement that lasts until the
// day it does not.
type Checksum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=graphene.blob.v1.Algorithm" json:"algorithm,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checksum) Reset() {
	*x = Checksum{}
	mi := &file_v1_blob_blob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checksum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checksum) ProtoMessage() {}

func (x *Checksum) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checksum.ProtoReflect.Descriptor instead.
func (*Checksum) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{1}
}

func (x *Checksum) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *Checksum) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Info is everything known about a blob without reading it.
type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Checksum      *Checksum              `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_v1_blob_blob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Info) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Info) GetChecksum() *Checksum {
	if x != nil {
		return x.Checksum
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_v1_blob_blob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type StatResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Exists bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	// Set only when it exists.
	Info          *Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_v1_blob_blob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{4}
}

func (x *StatResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatResponse) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*UploadRequest_Open
	//	*UploadRequest_Data
	Frame         isUploadRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_v1_blob_blob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{5}
}

func (x *UploadRequest) GetFrame() isUploadRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *UploadRequest) GetOpen() *UploadOpen {
	if x != nil {
		if x, ok := x.Frame.(*UploadRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *UploadRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Frame.(*UploadRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadRequest_Frame interface {
	isUploadRequest_Frame()
}

type UploadRequest_Open struct {
	// Exactly one, and first.
	Open *UploadOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type UploadRequest_Data struct {
	// Every frame after it. Order and integrity are the stream's.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadRequest_Open) isUploadRequest_Frame() {}

func (*UploadRequest_Data) isUploadRequest_Frame() {}

// UploadOpen is what the sender knows before sending.
//
// Both fields are optional: a sender that has not read the bytes yet
// cannot know either, and one that has should say, because a declaration
// is what turns a corrupted transfer into a refusal instead of a stored
// blob nobody notices is wrong.
type UploadOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksum      *Checksum              `protobuf:"bytes,1,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadOpen) Reset() {
	*x = UploadOpen{}
	mi := &file_v1_blob_blob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadOpen) ProtoMessage() {}

func (x *UploadOpen) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadOpen.ProtoReflect.Descriptor instead.
func (*UploadOpen) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{6}
}

func (x *UploadOpen) GetChecksum() *Checksum {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *UploadOpen) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *Info                  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_v1_blob_blob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{7}
}

func (x *UploadResponse) GetInfo() *Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type DownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Resume a broken transfer: start at this offset.
	Offset        uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_v1_blob_blob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *DownloadRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*DownloadResponse_Info
	//	*DownloadResponse_Data
	Frame         isDownloadResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_v1_blob_blob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadResponse) GetFrame() isDownloadResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *DownloadResponse) GetInfo() *Info {
	if x != nil {
		if x, ok := x.Frame.(*DownloadResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *DownloadResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Frame.(*DownloadResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isDownloadResponse_Frame interface {
	isDownloadResponse_Frame()
}

type DownloadResponse_Info struct {
	// Exactly one, and first.
	Info *Info `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type DownloadResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DownloadResponse_Info) isDownloadResponse_Frame() {}

func (*DownloadResponse_Data) isDownloadResponse_Frame() {}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_v1_blob_blob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_v1_blob_blob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_blob_blob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_v1_blob_blob_proto_rawDescGZIP(), []int{11}
}

var File_v1_blob_blob_proto protoreflect.FileDescriptor

const file_v1_blob_blob_proto_rawDesc = "" +
	"\n" +
	"\x12v1/blob/blob.proto\x12\x10graphene.blob.v1\"\x15\n" +
	"\x03Ref\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\bChecksum\x129\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1b.graphene.blob.v1.AlgorithmR\talgorithm\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"{\n" +
	"\x04Info\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.graphene.blob.v1.RefR\x03ref\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x126\n" +
	"\bchecksum\x18\x03 \x01(\v2\x1a.graphene.blob.v1.ChecksumR\bchecksum\"6\n" +
	"\vStatRequest\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.graphene.blob.v1.RefR\x03ref\"R\n" +
	"\fStatResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12*\n" +
	"\x04info\x18\x02 \x01(\v2\x16.graphene.blob.v1.InfoR\x04info\"b\n" +
	"\rUploadRequest\x122\n" +
	"\x04open\x18\x01 \x01(\v2\x1c.graphene.blob.v1.UploadOpenH\x00R\x04open\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05frame\"X\n" +
	"\n" +
	"UploadOpen\x126\n" +
	"\bchecksum\x18\x01 \x01(\v2\x1a.graphene.blob.v1.ChecksumR\bchecksum\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"<\n" +
	"\x0eUploadResponse\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.graphene.blob.v1.InfoR\x04info\"R\n" +
	"\x0fDownloadRequest\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.graphene.blob.v1.RefR\x03ref\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"_\n" +
	"\x10DownloadResponse\x12,\n" +
	"\x04info\x18\x01 \x01(\v2\x16.graphene.blob.v1.InfoH\x00R\x04info\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05frame\"8\n" +
	"\rDeleteRequest\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.graphene.blob.v1.RefR\x03ref\"\x10\n" +
	"\x0eDeleteResponse*<\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ALGORITHM_SHA256\x10\x012\xc5\x02\n" +
	"\vBlobService\x12E\n" +
	"\x04Stat\x12\x1d.graphene.blob.v1.StatRequest\x1a\x1e.graphene.blob.v1.StatResponse\x12M\n" +
	"\x06Upload\x12\x1f.graphene.blob.v1.UploadRequest\x1a .graphene.blob.v1.UploadResponse(\x01\x12S\n" +
	"\bDownload\x12!.graphene.blob.v1.DownloadRequest\x1a\".graphene.blob.v1.DownloadResponse0\x01\x12K\n" +
	"\x06Delete\x12\x1f.graphene.blob.v1.DeleteRequest\x1a .graphene.blob.v1.DeleteResponseB2Z0github.com/graphene-ci/graphenepb/v1/blob;blobpbb\x06proto3"

var (
	file_v1_blob_blob_proto_rawDescOnce sync.Once
	file_v1_blob_blob_proto_rawDescData []byte
)

func file_v1_blob_blob_proto_rawDescGZIP() []byte {
	file_v1_blob_blob_proto_rawDescOnce.Do(func() {
		file_v1_blob_blob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_blob_blob_proto_rawDesc), len(file_v1_blob_blob_proto_rawDesc)))
	})
	return file_v1_blob_blob_proto_rawDescData
}

var file_v1_blob_blob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_blob_blob_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_blob_blob_proto_goTypes = []any{
	(Algorithm)(0),           // 0: graphene.blob.v1.Algorithm
	(*Ref)(nil),              // 1: graphene.blob.v1.Ref
	(*Checksum)(nil),         // 2: graphene.blob.v1.Checksum
	(*Info)(nil),             // 3: graphene.blob.v1.Info
	(*StatRequest)(nil),      // 4: graphene.blob.v1.StatRequest
	(*StatResponse)(nil),     // 5: graphene.blob.v1.StatResponse
	(*UploadRequest)(nil),    // 6: graphene.blob.v1.UploadRequest
	(*UploadOpen)(nil),       // 7: graphene.blob.v1.UploadOpen
	(*UploadResponse)(nil),   // 8: graphene.blob.v1.UploadResponse
	(*DownloadRequest)(nil),  // 9: graphene.blob.v1.DownloadRequest
	(*DownloadResponse)(nil), // 10: graphene.blob.v1.DownloadResponse
	(*DeleteRequest)(nil),    // 11: graphene.blob.v1.DeleteRequest
	(*DeleteResponse)(nil),   // 12: graphene.blob.v1.DeleteResponse
}
var file_v1_blob_blob_proto_depIdxs = []int32{
	0,  // 0: graphene.blob.v1.Checksum.algorithm:type_name -> graphene.blob.v1.Algorithm
	1,  // 1: graphene.blob.v1.Info.ref:type_name -> graphene.blob.v1.Ref
	2,  // 2: graphene.blob.v1.Info.checksum:type_name -> graphene.blob.v1.Checksum
	1,  // 3: graphene.blob.v1.StatRequest.ref:type_name -> graphene.blob.v1.Ref
	3,  // 4: graphene.blob.v1.StatResponse.info:type_name -> graphene.blob.v1.Info
	7,  // 5: graphene.blob.v1.UploadRequest.open:type_name -> graphene.blob.v1.UploadOpen
	2,  // 6: graphene.blob.v1.UploadOpen.checksum:type_name -> graphene.blob.v1.Checksum
	3,  // 7: graphene.blob.v1.UploadResponse.info:type_name -> graphene.blob.v1.Info
	1,  // 8: graphene.blob.v1.DownloadRequest.ref:type_name -> graphene.blob.v1.Ref
	3,  // 9: graphene.blob.v1.DownloadResponse.info:type_name -> graphene.blob.v1.Info
	1,  // 10: graphene.blob.v1.DeleteRequest.ref:type_name -> graphene.blob.v1.Ref
	4,  // 11: graphene.blob.v1.BlobService.Stat:input_type -> graphene.blob.v1.StatRequest
	6,  // 12: graphene.blob.v1.BlobService.Upload:input_type -> graphene.blob.v1.UploadRequest
	9,  // 13: graphene.blob.v1.BlobService.Download:input_type -> graphene.blob.v1.DownloadRequest
	11, // 14: graphene.blob.v1.BlobService.Delete:input_type -> graphene.blob.v1.DeleteRequest
	5,  // 15: graphene.blob.v1.BlobService.Stat:output_type -> graphene.blob.v1.StatResponse
	8,  // 16: graphene.blob.v1.BlobService.Upload:output_type -> graphene.blob.v1.UploadResponse
	10, // 17: graphene.blob.v1.BlobService.Download:output_type -> graphene.blob.v1.DownloadResponse
	12, // 18: graphene.blob.v1.BlobService.Delete:output_type -> graphene.blob.v1.DeleteResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_blob_blob_proto_init() }
func file_v1_blob_blob_proto_init() {
	if File_v1_blob_blob_proto != nil {
		return
	}
	file_v1_blob_blob_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadRequest_Open)(nil),
		(*UploadRequest_Data)(nil),
	}
	file_v1_blob_blob_proto_msgTypes[9].OneofWrappers = []any{
		(*DownloadResponse_Info)(nil),
		(*DownloadResponse_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_blob_blob_proto_rawDesc), len(file_v1_blob_blob_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_blob_blob_proto_goTypes,
		DependencyIndexes: file_v1_blob_blob_proto_depIdxs,
		EnumInfos:         file_v1_blob_blob_proto_enumTypes,
		MessageInfos:      file_v1_blob_blob_proto_msgTypes,
	}.Build()
	File_v1_blob_blob_proto = out.File
	file_v1_blob_blob_proto_goTypes = nil
	file_v1_blob_blob_proto_depIdxs = nil
}
